// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: io/core/a_rpc_distribution.proto

package com.passkit.grpc;

public final class ARpcDistribution {
  private ARpcDistribution() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n io/core/a_rpc_distribution.proto\022\002io\032\034" +
      "google/api/annotations.proto\032\033google/pro" +
      "tobuf/empty.proto\032,protoc-gen-swagger/op" +
      "tions/annotations.proto\032\036io/common/commo" +
      "n_objects.proto\032\034io/common/distribution." +
      "proto2\226\005\n\014Distribution\022\252\002\n\020sendWelcomeEm" +
      "ail\022\034.io.EmailDistributionRequest\032\026.goog" +
      "le.protobuf.Empty\"\337\001\202\323\344\223\002\030\"\023/distributio" +
      "n/email:\001*\222A\275\001\022\022Send Welcome Email\032.Send" +
      "s a welcome email to an individual recor" +
      "d.J0\n\003400\022)\n\'There is a problem with the" +
      " input data.J\036\n\003404\022\027\n\025Record was not fo" +
      "und.J%\n\003500\022\036\n\034There was an internal err" +
      "or.\022\330\002\n\021getSmartPasssLink\022\030.io.SmartPass" +
      "LinkRequest\032\007.io.Url\"\237\002\202\323\344\223\002 \"\033/distribu" +
      "tion/smartpasslink:\001*\222A\365\001\022\022Get SmartPass" +
      " Link\032fGet SmartPass returns encrypted S" +
      "martPass link based on a pass payload fo" +
      "r a member, coupon or ticket.J0\n\003400\022)\n\'" +
      "There is a problem with the input data.J" +
      "\036\n\003404\022\027\n\025Record was not found.J%\n\003500\022\036" +
      "\n\034There was an internal error.BG\n\020com.pa" +
      "sskit.grpcZ$stash.passkit.com/io/model/s" +
      "dk/go/io\252\002\014PassKit.GRPCb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
          grpc.gateway.protoc_gen_swagger.options.Annotations.getDescriptor(),
          com.passkit.grpc.CommonObjects.getDescriptor(),
          com.passkit.grpc.Distribution.getDescriptor(),
        });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    registry.add(grpc.gateway.protoc_gen_swagger.options.Annotations.openapiv2Operation);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
    grpc.gateway.protoc_gen_swagger.options.Annotations.getDescriptor();
    com.passkit.grpc.CommonObjects.getDescriptor();
    com.passkit.grpc.Distribution.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
