// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: io/core/a_rpc_others.proto

package com.passkit.grpc;

public final class ARpcOthers {
  private ARpcOthers() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032io/core/a_rpc_others.proto\022\002io\032\034google" +
      "/api/annotations.proto\032\033google/protobuf/" +
      "empty.proto\032.protoc-gen-openapiv2/option" +
      "s/annotations.proto\032\036io/common/common_ob" +
      "jects.proto\032\027io/common/project.proto\032\032io" +
      "/common/pagination.proto\032\026io/common/filt" +
      "er.proto\032\033io/common/integration.proto\032\022i" +
      "o/user/user.proto2\233\031\n\005Users\022@\n\ncreateUse" +
      "r\022\013.io.NewUser\032\023.io.NewUserResponse\"\020\202\323\344" +
      "\223\002\n\"\005/user:\001*\0225\n\007newUser\022\013.io.NewUser\032\007." +
      "io.JWT\"\024\202\323\344\223\002\016\"\t/user/new:\001*\022A\n\006verify\022\021" +
      ".io.VerifyRequest\032\013.io.Boolean\"\027\202\323\344\223\002\021\032\014" +
      "/user/verify:\001*\022^\n\027resendVerificationEma" +
      "il\022\026.google.protobuf.Empty\032\013.io.Boolean\"" +
      "\036\202\323\344\223\002\030\"\023/user/verify/resend:\001*\022M\n\007getUs" +
      "er\022\026.google.protobuf.Empty\032\023.io.GetUserR" +
      "esponse\"\025\202\323\344\223\002\017\022\r/user/profile\0224\n\005login\022" +
      "\017.io.Credentials\032\007.io.JWT\"\021\202\323\344\223\002\013\"\006/logi" +
      "n:\001*\022P\n\rresetPassword\022\017.io.Credentials\032\026" +
      ".google.protobuf.Empty\"\026\202\323\344\223\002\020\032\013/user/re" +
      "set:\001*\022^\n\025sendPasswordResetLink\022\014.io.Use" +
      "rname\032\026.google.protobuf.Empty\"\037\202\323\344\223\002\031\"\024/" +
      "user/reset/password:\001*\022a\n\016changePassword" +
      "\022\026.io.PasswordResetInput\032\026.google.protob" +
      "uf.Empty\"\037\202\323\344\223\002\031\032\024/user/reset/password:\001" +
      "*\022N\n\013changeEmail\022\t.io.Email\032\026.google.pro" +
      "tobuf.Empty\"\034\202\323\344\223\002\026\"\021/user/reset/email:\001" +
      "*\022g\n\022confirmEmailChange\022\033.io.ConfirmEmai" +
      "lChangeInput\032\026.google.protobuf.Empty\"\034\202\323" +
      "\344\223\002\026\032\021/user/reset/email:\001*\022[\n\021updateComp" +
      "anyName\022\017.io.CompanyName\032\026.google.protob" +
      "uf.Empty\"\035\202\323\344\223\002\027\032\022/user/company/name:\001*\022" +
      "`\n!getProjectsForUserQueryDeprecated\022\016.i" +
      "o.Pagination\032\013.io.Project\"\034\202\323\344\223\002\026\022\024/proj" +
      "ects/user/query0\001\022T\n\032getProjectsQueryDep" +
      "recated\022\016.io.Pagination\032\013.io.Project\"\027\202\323" +
      "\344\223\002\021\022\017/projects/query0\001\022U\n\027getProjectsFo" +
      "rUserQuery\022\013.io.Filters\032\013.io.Project\"\036\202\323" +
      "\344\223\002\030\"\023/projects/user/list:\001*0\001\022I\n\020getPro" +
      "jectsQuery\022\013.io.Filters\032\013.io.Project\"\031\202\323" +
      "\344\223\002\023\"\016/projects/list:\001*0\001\022B\n\020getProjectB" +
      "yUuid\022\006.io.Id\032\013.io.Project\"\031\202\323\344\223\002\023\022\021/pro" +
      "jects/id/{id}\022c\n getProjectAndTemplateBy" +
      "ShortCode\022\006.io.Id\032\034.io.ProjectByShortCod" +
      "eResult\"\031\202\323\344\223\002\023\022\021/projects/sc/{id}\022]\n\022ge" +
      "tProjectsForUser\022\027.io.ProjectStatusFilte" +
      "r\032\013.io.Project\"\037\202\323\344\223\002\031\022\027/projects/user/{" +
      "status}0\001\022Q\n\013getProjects\022\027.io.ProjectSta" +
      "tusFilter\032\013.io.Project\"\032\202\323\344\223\002\024\022\022/project" +
      "s/{status}0\001\022[\n\020getScannerConfig\022\026.googl" +
      "e.protobuf.Empty\032\030.io.ScannerConfigurati" +
      "on\"\025\202\323\344\223\002\017\022\r/user/scanner\022a\n\023createScann" +
      "erConfig\022\030.io.ScannerConfiguration\032\026.goo" +
      "gle.protobuf.Empty\"\030\202\323\344\223\002\022\"\r/user/scanne" +
      "r:\001*\022c\n\023updateScannerConfig\022\030.io.Scanner" +
      "Configuration\032\030.io.ScannerConfiguration\"" +
      "\030\202\323\344\223\002\022\032\r/user/scanner:\001*\022\255\002\n\033createAuth" +
      "orizationResource\022\036.io.OAuth2Authorizati" +
      "onRequest\032\006.io.Id\"\345\001\222A\313\001\022-Requests an ac" +
      "cess token from an external API\0322Creates" +
      " a record of an oauth2 access token requ" +
      "estJ0\n\003400\022)\n\'There is a problem with th" +
      "e input data.J4\n\003403\022-\n+Returned when th" +
      "e user lacks authorization.\202\323\344\223\002\020\"\013/user" +
      "/oauth:\001*\022\371\001\n\033deleteAuthorizationResourc" +
      "e\022\006.io.Id\032\026.google.protobuf.Empty\"\271\001\222A\235\001" +
      "\022\035Delete Authorization Resource\032:Deletes" +
      " an oauth2 authorization resource from t" +
      "he databaseJ!\n\003403\022\032\n\030User lacks authori" +
      "zationJ\035\n\003404\022\026\n\024Record was not found\202\323\344" +
      "\223\002\022*\020/user/oauth/{id}\022\277\005\n\rdeleteAccount\022" +
      "\030.io.DeleteAccountRequest\032\026.google.proto" +
      "buf.Empty\"\373\004\222A\337\004\022\016Delete Account\032\323\003Perma" +
      "nently and irrecoverably delete a PassKi" +
      "t account, including all projects, asset" +
      "s, passes and pass holder information. A" +
      "ll current passes will be invalidated ma" +
      "king them impossible to be reactivate. T" +
      "his action cannot be undone. A confirmat" +
      "ion will be sent by email once the reque" +
      "st has been executed. To delete your acc" +
      "ount, please delete all of projects belo" +
      "ng to the owner and subusers\' accounts. " +
      "Only users with owner permission can exe" +
      "cute account deletion.J0\n\003400\022)\n\'There i" +
      "s a problem with the input data.J\036\n\003404\022" +
      "\027\n\025Record was not found.J%\n\003500\022\036\n\034There" +
      " was an internal error.\202\323\344\223\002\022*\r/user/acc" +
      "ount:\001*2\303\032\n\014Integrations\022\201\002\n\022createInteg" +
      "rations\022\026.io.IntegrationConfigs\032\006.io.Id\"" +
      "\312\001\222A\242\001\022\023Create Integrations\032#Sets up int" +
      "egration configurations.J0\n\003400\022)\n\'There" +
      " is a problem with the input data.J4\n\00340" +
      "3\022-\n+Returned when the user lacks author" +
      "ization.\202\323\344\223\002\036\"\031/integrations/integratio" +
      "n:\001*\022\367\001\n\017getIntegrations\022\023.io.ProtocolId" +
      "Input\032\026.io.IntegrationConfigs\"\266\001\222A}\022\020Get" +
      " Integrations\032%Retrieves integration con" +
      "figurations.J\"\n\003403\022\033\n\031User lacks author" +
      "ization.J\036\n\003404\022\027\n\025Record was not found." +
      "\202\323\344\223\0020\022./integrations/integration/{proto" +
      "col}/{classId}\022\343\002\n\022updateIntegrations\022\026." +
      "io.IntegrationConfigs\032\006.io.Id\"\254\002\222A\204\002\022\023Up" +
      "date Integrations\032\036Updates an integratio" +
      "n record.J0\n\003400\022)\n\'There is a problem w" +
      "ith the input data.J\"\n\003403\022\033\n\031User lacks" +
      " authorization.J\036\n\003404\022\027\n\025Record was not" +
      " found.JW\n\003503\022P\nNServer is unavailable." +
      " Back off for 250ms and repeat request u" +
      "ntil successful.\202\323\344\223\002\036\032\031/integrations/in" +
      "tegration:\001*\022\365\001\n\022deleteIntegrations\022\023.io" +
      ".ProtocolIdInput\032\026.google.protobuf.Empty" +
      "\"\261\001\222Ax\022\023Delete Integrations\032\035Deletes an " +
      "integration recordJ\"\n\003403\022\033\n\031User lacks " +
      "authorization.J\036\n\003404\022\027\n\025Record was not " +
      "found.\202\323\344\223\0020*./integrations/integration/" +
      "{protocol}/{classId}\022\310\002\n\026createSinkSubsc" +
      "ription\022\024.io.SinkSubscription\032\006.io.Id\"\217\002" +
      "\222A\356\001\022\030Create Sink Subscription\032jCreates " +
      "a sink subscription so that PassKit can " +
      "send a message to a URL after certain ev" +
      "ent has completed.J0\n\003400\022)\n\'There is a " +
      "problem with the input data.J4\n\003403\022-\n+R" +
      "eturned when the user lacks authorizatio" +
      "n.\202\323\344\223\002\027\"\022/integrations/sink:\001*\022\203\002\n\023getS" +
      "inkSubscription\022\027.io.SubscriptionRequest" +
      "\032\024.io.SinkSubscription\"\274\001\222A\202\001\022\025Get Sink " +
      "Subscription\032%Retrieves a sink subscript" +
      "ion config.J\"\n\003403\022\033\n\031User lacks authori" +
      "zation.J\036\n\003404\022\027\n\025Record was not found.\202" +
      "\323\344\223\0020\022./integrations/sink/{protocol}/{su" +
      "bscriptionId}\022\326\002\n\037listSinkSubscriptionsD" +
      "eprecated\022\031.io.ListRequestDeprecated\032\024.i" +
      "o.SinkSubscription\"\377\001\222A\333\001\022$List Sink Sub" +
      "scriptions [DEPRECATED]\032o[DEPRECATED: OR" +
      " operator is not supported] List all sin" +
      "k subscriptions for a given segment. Sup" +
      "port pagination.J\"\n\003403\022\033\n\031User lacks au" +
      "thorization.J\036\n\003404\022\027\n\025Record was not fo" +
      "und.\202\323\344\223\002\032\022\030/integrations/sinks/list0\001\022\215" +
      "\002\n\025listSinkSubscriptions\022\017.io.ListReques" +
      "t\032\024.io.SinkSubscription\"\312\001\222A\243\001\022\027List Sin" +
      "k Subscriptions\032DList all sink subscript" +
      "ions for a given segment. Support pagina" +
      "tion.J\"\n\003403\022\033\n\031User lacks authorization" +
      ".J\036\n\003404\022\027\n\025Record was not found.\202\323\344\223\002\035\"" +
      "\030/integrations/sinks/list:\001*0\001\022\350\002\n\026updat" +
      "eSinkSubscription\022\024.io.SinkSubscription\032" +
      "\006.io.Id\"\257\002\222A\216\002\022\030Update Sink Subscription" +
      "\032#Updates a sink subscription record.J0\n" +
      "\003400\022)\n\'There is a problem with the inpu" +
      "t data.J\"\n\003403\022\033\n\031User lacks authorizati" +
      "on.J\036\n\003404\022\027\n\025Record was not found.JW\n\0035" +
      "03\022P\nNServer is unavailable. Back off fo" +
      "r 250ms and repeat request until success" +
      "ful.\202\323\344\223\002\027\032\022/integrations/sink:\001*\022\211\002\n\026de" +
      "leteSinkSubscription\022\027.io.SubscriptionRe" +
      "quest\032\026.google.protobuf.Empty\"\275\001\222A\203\001\022\030De" +
      "lete Sink Subscription\032#Deletes an sink " +
      "subscription recordJ\"\n\003403\022\033\n\031User lacks" +
      " authorization.J\036\n\003404\022\027\n\025Record was not" +
      " found.\202\323\344\223\0020*./integrations/sink/{proto" +
      "col}/{subscriptionId}\022\357\001\n\032getSampleSubsc" +
      "riptionEvent\022\006.io.Id\032\024.io.SinkSubscripti" +
      "on\"\262\001\222A\215\001\022\035Get Sample Subscription Event" +
      "\032(Retrieves a sample subscription payloa" +
      "d.J\"\n\003403\022\033\n\031User lacks authorization.J\036" +
      "\n\003404\022\027\n\025Record was not found.\202\323\344\223\002\033\022\031/i" +
      "ntegrations/sink/sample\022\263\001\n\016callDynamicA" +
      "pi\022\023.io.DynamicApiInput\032\026.io.DynamicApiR" +
      "esponse\"t\222AU\022\020Call Dynamic API\032AMakes an" +
      " API call to the third party app integra" +
      "ted with PassKit.\202\323\344\223\002\026\"\021/integrations/a" +
      "pi:\001*BG\n\020com.passkit.grpcZ$stash.passkit" +
      ".com/io/model/sdk/go/io\252\002\014PassKit.Grpcb\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
          grpc.gateway.protoc_gen_openapiv2.options.Annotations.getDescriptor(),
          com.passkit.grpc.CommonObjects.getDescriptor(),
          com.passkit.grpc.ProjectOuterClass.getDescriptor(),
          com.passkit.grpc.PaginationOuterClass.getDescriptor(),
          com.passkit.grpc.Filter.getDescriptor(),
          com.passkit.grpc.Integration.getDescriptor(),
          com.passkit.grpc.User.getDescriptor(),
        });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    registry.add(grpc.gateway.protoc_gen_openapiv2.options.Annotations.openapiv2Operation);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
    grpc.gateway.protoc_gen_openapiv2.options.Annotations.getDescriptor();
    com.passkit.grpc.CommonObjects.getDescriptor();
    com.passkit.grpc.ProjectOuterClass.getDescriptor();
    com.passkit.grpc.PaginationOuterClass.getDescriptor();
    com.passkit.grpc.Filter.getDescriptor();
    com.passkit.grpc.Integration.getDescriptor();
    com.passkit.grpc.User.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
