// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: io/common/billing.proto
// Protobuf Java Version: 4.27.2

package com.passkit.grpc;

public final class Billing {
  private Billing() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      Billing.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface QuotaOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.Quota)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * key is one of pk.MeteredEventType
     * </pre>
     *
     * <code>map&lt;uint32, .io.QuotaDetails&gt; details = 1;</code>
     */
    int getDetailsCount();
    /**
     * <pre>
     * key is one of pk.MeteredEventType
     * </pre>
     *
     * <code>map&lt;uint32, .io.QuotaDetails&gt; details = 1;</code>
     */
    boolean containsDetails(
        int key);
    /**
     * Use {@link #getDetailsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.Integer, com.passkit.grpc.Billing.QuotaDetails>
    getDetails();
    /**
     * <pre>
     * key is one of pk.MeteredEventType
     * </pre>
     *
     * <code>map&lt;uint32, .io.QuotaDetails&gt; details = 1;</code>
     */
    java.util.Map<java.lang.Integer, com.passkit.grpc.Billing.QuotaDetails>
    getDetailsMap();
    /**
     * <pre>
     * key is one of pk.MeteredEventType
     * </pre>
     *
     * <code>map&lt;uint32, .io.QuotaDetails&gt; details = 1;</code>
     */
    /* nullable */
com.passkit.grpc.Billing.QuotaDetails getDetailsOrDefault(
        int key,
        /* nullable */
com.passkit.grpc.Billing.QuotaDetails defaultValue);
    /**
     * <pre>
     * key is one of pk.MeteredEventType
     * </pre>
     *
     * <code>map&lt;uint32, .io.QuotaDetails&gt; details = 1;</code>
     */
    com.passkit.grpc.Billing.QuotaDetails getDetailsOrThrow(
        int key);
  }
  /**
   * Protobuf type {@code io.Quota}
   */
  public static final class Quota extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:io.Quota)
      QuotaOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 2,
        /* suffix= */ "",
        Quota.class.getName());
    }
    // Use Quota.newBuilder() to construct.
    private Quota(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Quota() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.passkit.grpc.Billing.internal_static_io_Quota_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 1:
          return internalGetDetails();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.passkit.grpc.Billing.internal_static_io_Quota_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.passkit.grpc.Billing.Quota.class, com.passkit.grpc.Billing.Quota.Builder.class);
    }

    public static final int DETAILS_FIELD_NUMBER = 1;
    private static final class DetailsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.Integer, com.passkit.grpc.Billing.QuotaDetails> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.Integer, com.passkit.grpc.Billing.QuotaDetails>newDefaultInstance(
                  com.passkit.grpc.Billing.internal_static_io_Quota_DetailsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.UINT32,
                  0,
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.passkit.grpc.Billing.QuotaDetails.getDefaultInstance());
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        java.lang.Integer, com.passkit.grpc.Billing.QuotaDetails> details_;
    private com.google.protobuf.MapField<java.lang.Integer, com.passkit.grpc.Billing.QuotaDetails>
    internalGetDetails() {
      if (details_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            DetailsDefaultEntryHolder.defaultEntry);
      }
      return details_;
    }
    public int getDetailsCount() {
      return internalGetDetails().getMap().size();
    }
    /**
     * <pre>
     * key is one of pk.MeteredEventType
     * </pre>
     *
     * <code>map&lt;uint32, .io.QuotaDetails&gt; details = 1;</code>
     */
    @java.lang.Override
    public boolean containsDetails(
        int key) {

      return internalGetDetails().getMap().containsKey(key);
    }
    /**
     * Use {@link #getDetailsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, com.passkit.grpc.Billing.QuotaDetails> getDetails() {
      return getDetailsMap();
    }
    /**
     * <pre>
     * key is one of pk.MeteredEventType
     * </pre>
     *
     * <code>map&lt;uint32, .io.QuotaDetails&gt; details = 1;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.Integer, com.passkit.grpc.Billing.QuotaDetails> getDetailsMap() {
      return internalGetDetails().getMap();
    }
    /**
     * <pre>
     * key is one of pk.MeteredEventType
     * </pre>
     *
     * <code>map&lt;uint32, .io.QuotaDetails&gt; details = 1;</code>
     */
    @java.lang.Override
    public /* nullable */
com.passkit.grpc.Billing.QuotaDetails getDetailsOrDefault(
        int key,
        /* nullable */
com.passkit.grpc.Billing.QuotaDetails defaultValue) {

      java.util.Map<java.lang.Integer, com.passkit.grpc.Billing.QuotaDetails> map =
          internalGetDetails().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * key is one of pk.MeteredEventType
     * </pre>
     *
     * <code>map&lt;uint32, .io.QuotaDetails&gt; details = 1;</code>
     */
    @java.lang.Override
    public com.passkit.grpc.Billing.QuotaDetails getDetailsOrThrow(
        int key) {

      java.util.Map<java.lang.Integer, com.passkit.grpc.Billing.QuotaDetails> map =
          internalGetDetails().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessage
        .serializeIntegerMapTo(
          output,
          internalGetDetails(),
          DetailsDefaultEntryHolder.defaultEntry,
          1);
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.Integer, com.passkit.grpc.Billing.QuotaDetails> entry
           : internalGetDetails().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, com.passkit.grpc.Billing.QuotaDetails>
        details__ = DetailsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, details__);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.passkit.grpc.Billing.Quota)) {
        return super.equals(obj);
      }
      com.passkit.grpc.Billing.Quota other = (com.passkit.grpc.Billing.Quota) obj;

      if (!internalGetDetails().equals(
          other.internalGetDetails())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetDetails().getMap().isEmpty()) {
        hash = (37 * hash) + DETAILS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetDetails().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.passkit.grpc.Billing.Quota parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.passkit.grpc.Billing.Quota parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.passkit.grpc.Billing.Quota parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.passkit.grpc.Billing.Quota parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.passkit.grpc.Billing.Quota parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.passkit.grpc.Billing.Quota parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.passkit.grpc.Billing.Quota parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.passkit.grpc.Billing.Quota parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.passkit.grpc.Billing.Quota parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.passkit.grpc.Billing.Quota parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.passkit.grpc.Billing.Quota parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.passkit.grpc.Billing.Quota parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.passkit.grpc.Billing.Quota prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.Quota}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.Quota)
        com.passkit.grpc.Billing.QuotaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.passkit.grpc.Billing.internal_static_io_Quota_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
          int number) {
        switch (number) {
          case 1:
            return internalGetDetails();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableDetails();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.passkit.grpc.Billing.internal_static_io_Quota_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.passkit.grpc.Billing.Quota.class, com.passkit.grpc.Billing.Quota.Builder.class);
      }

      // Construct using com.passkit.grpc.Billing.Quota.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        internalGetMutableDetails().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.passkit.grpc.Billing.internal_static_io_Quota_descriptor;
      }

      @java.lang.Override
      public com.passkit.grpc.Billing.Quota getDefaultInstanceForType() {
        return com.passkit.grpc.Billing.Quota.getDefaultInstance();
      }

      @java.lang.Override
      public com.passkit.grpc.Billing.Quota build() {
        com.passkit.grpc.Billing.Quota result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.passkit.grpc.Billing.Quota buildPartial() {
        com.passkit.grpc.Billing.Quota result = new com.passkit.grpc.Billing.Quota(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.passkit.grpc.Billing.Quota result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.details_ = internalGetDetails().build(DetailsDefaultEntryHolder.defaultEntry);
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.passkit.grpc.Billing.Quota) {
          return mergeFrom((com.passkit.grpc.Billing.Quota)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.passkit.grpc.Billing.Quota other) {
        if (other == com.passkit.grpc.Billing.Quota.getDefaultInstance()) return this;
        internalGetMutableDetails().mergeFrom(
            other.internalGetDetails());
        bitField0_ |= 0x00000001;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.google.protobuf.MapEntry<java.lang.Integer, com.passkit.grpc.Billing.QuotaDetails>
                details__ = input.readMessage(
                    DetailsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableDetails().ensureBuilderMap().put(
                    details__.getKey(), details__.getValue());
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private static final class DetailsConverter implements com.google.protobuf.MapFieldBuilder.Converter<java.lang.Integer, com.passkit.grpc.Billing.QuotaDetailsOrBuilder, com.passkit.grpc.Billing.QuotaDetails> {
        @java.lang.Override
        public com.passkit.grpc.Billing.QuotaDetails build(com.passkit.grpc.Billing.QuotaDetailsOrBuilder val) {
          if (val instanceof com.passkit.grpc.Billing.QuotaDetails) { return (com.passkit.grpc.Billing.QuotaDetails) val; }
          return ((com.passkit.grpc.Billing.QuotaDetails.Builder) val).build();
        }

        @java.lang.Override
        public com.google.protobuf.MapEntry<java.lang.Integer, com.passkit.grpc.Billing.QuotaDetails> defaultEntry() {
          return DetailsDefaultEntryHolder.defaultEntry;
        }
      };
      private static final DetailsConverter detailsConverter = new DetailsConverter();

      private com.google.protobuf.MapFieldBuilder<
          java.lang.Integer, com.passkit.grpc.Billing.QuotaDetailsOrBuilder, com.passkit.grpc.Billing.QuotaDetails, com.passkit.grpc.Billing.QuotaDetails.Builder> details_;
      private com.google.protobuf.MapFieldBuilder<java.lang.Integer, com.passkit.grpc.Billing.QuotaDetailsOrBuilder, com.passkit.grpc.Billing.QuotaDetails, com.passkit.grpc.Billing.QuotaDetails.Builder>
          internalGetDetails() {
        if (details_ == null) {
          return new com.google.protobuf.MapFieldBuilder<>(detailsConverter);
        }
        return details_;
      }
      private com.google.protobuf.MapFieldBuilder<java.lang.Integer, com.passkit.grpc.Billing.QuotaDetailsOrBuilder, com.passkit.grpc.Billing.QuotaDetails, com.passkit.grpc.Billing.QuotaDetails.Builder>
          internalGetMutableDetails() {
        if (details_ == null) {
          details_ = new com.google.protobuf.MapFieldBuilder<>(detailsConverter);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return details_;
      }
      public int getDetailsCount() {
        return internalGetDetails().ensureBuilderMap().size();
      }
      /**
       * <pre>
       * key is one of pk.MeteredEventType
       * </pre>
       *
       * <code>map&lt;uint32, .io.QuotaDetails&gt; details = 1;</code>
       */
      @java.lang.Override
      public boolean containsDetails(
          int key) {

        return internalGetDetails().ensureBuilderMap().containsKey(key);
      }
      /**
       * Use {@link #getDetailsMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, com.passkit.grpc.Billing.QuotaDetails> getDetails() {
        return getDetailsMap();
      }
      /**
       * <pre>
       * key is one of pk.MeteredEventType
       * </pre>
       *
       * <code>map&lt;uint32, .io.QuotaDetails&gt; details = 1;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.Integer, com.passkit.grpc.Billing.QuotaDetails> getDetailsMap() {
        return internalGetDetails().getImmutableMap();
      }
      /**
       * <pre>
       * key is one of pk.MeteredEventType
       * </pre>
       *
       * <code>map&lt;uint32, .io.QuotaDetails&gt; details = 1;</code>
       */
      @java.lang.Override
      public /* nullable */
com.passkit.grpc.Billing.QuotaDetails getDetailsOrDefault(
          int key,
          /* nullable */
com.passkit.grpc.Billing.QuotaDetails defaultValue) {

        java.util.Map<java.lang.Integer, com.passkit.grpc.Billing.QuotaDetailsOrBuilder> map = internalGetMutableDetails().ensureBuilderMap();
        return map.containsKey(key) ? detailsConverter.build(map.get(key)) : defaultValue;
      }
      /**
       * <pre>
       * key is one of pk.MeteredEventType
       * </pre>
       *
       * <code>map&lt;uint32, .io.QuotaDetails&gt; details = 1;</code>
       */
      @java.lang.Override
      public com.passkit.grpc.Billing.QuotaDetails getDetailsOrThrow(
          int key) {

        java.util.Map<java.lang.Integer, com.passkit.grpc.Billing.QuotaDetailsOrBuilder> map = internalGetMutableDetails().ensureBuilderMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return detailsConverter.build(map.get(key));
      }
      public Builder clearDetails() {
        bitField0_ = (bitField0_ & ~0x00000001);
        internalGetMutableDetails().clear();
        return this;
      }
      /**
       * <pre>
       * key is one of pk.MeteredEventType
       * </pre>
       *
       * <code>map&lt;uint32, .io.QuotaDetails&gt; details = 1;</code>
       */
      public Builder removeDetails(
          int key) {

        internalGetMutableDetails().ensureBuilderMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, com.passkit.grpc.Billing.QuotaDetails>
          getMutableDetails() {
        bitField0_ |= 0x00000001;
        return internalGetMutableDetails().ensureMessageMap();
      }
      /**
       * <pre>
       * key is one of pk.MeteredEventType
       * </pre>
       *
       * <code>map&lt;uint32, .io.QuotaDetails&gt; details = 1;</code>
       */
      public Builder putDetails(
          int key,
          com.passkit.grpc.Billing.QuotaDetails value) {

        if (value == null) { throw new NullPointerException("map value"); }
        internalGetMutableDetails().ensureBuilderMap()
            .put(key, value);
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       * key is one of pk.MeteredEventType
       * </pre>
       *
       * <code>map&lt;uint32, .io.QuotaDetails&gt; details = 1;</code>
       */
      public Builder putAllDetails(
          java.util.Map<java.lang.Integer, com.passkit.grpc.Billing.QuotaDetails> values) {
        for (java.util.Map.Entry<java.lang.Integer, com.passkit.grpc.Billing.QuotaDetails> e : values.entrySet()) {
          if (e.getKey() == null || e.getValue() == null) {
            throw new NullPointerException();
          }
        }
        internalGetMutableDetails().ensureBuilderMap()
            .putAll(values);
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       * key is one of pk.MeteredEventType
       * </pre>
       *
       * <code>map&lt;uint32, .io.QuotaDetails&gt; details = 1;</code>
       */
      public com.passkit.grpc.Billing.QuotaDetails.Builder putDetailsBuilderIfAbsent(
          int key) {
        java.util.Map<java.lang.Integer, com.passkit.grpc.Billing.QuotaDetailsOrBuilder> builderMap = internalGetMutableDetails().ensureBuilderMap();
        com.passkit.grpc.Billing.QuotaDetailsOrBuilder entry = builderMap.get(key);
        if (entry == null) {
          entry = com.passkit.grpc.Billing.QuotaDetails.newBuilder();
          builderMap.put(key, entry);
        }
        if (entry instanceof com.passkit.grpc.Billing.QuotaDetails) {
          entry = ((com.passkit.grpc.Billing.QuotaDetails) entry).toBuilder();
          builderMap.put(key, entry);
        }
        return (com.passkit.grpc.Billing.QuotaDetails.Builder) entry;
      }

      // @@protoc_insertion_point(builder_scope:io.Quota)
    }

    // @@protoc_insertion_point(class_scope:io.Quota)
    private static final com.passkit.grpc.Billing.Quota DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.passkit.grpc.Billing.Quota();
    }

    public static com.passkit.grpc.Billing.Quota getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Quota>
        PARSER = new com.google.protobuf.AbstractParser<Quota>() {
      @java.lang.Override
      public Quota parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Quota> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Quota> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.passkit.grpc.Billing.Quota getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface QuotaDetailsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.QuotaDetails)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 quota = 1;</code>
     * @return The quota.
     */
    int getQuota();

    /**
     * <pre>
     * contains bitmask of pk.Status
     * </pre>
     *
     * <code>uint64 status = 2;</code>
     * @return The status.
     */
    long getStatus();
  }
  /**
   * Protobuf type {@code io.QuotaDetails}
   */
  public static final class QuotaDetails extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:io.QuotaDetails)
      QuotaDetailsOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 2,
        /* suffix= */ "",
        QuotaDetails.class.getName());
    }
    // Use QuotaDetails.newBuilder() to construct.
    private QuotaDetails(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private QuotaDetails() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.passkit.grpc.Billing.internal_static_io_QuotaDetails_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.passkit.grpc.Billing.internal_static_io_QuotaDetails_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.passkit.grpc.Billing.QuotaDetails.class, com.passkit.grpc.Billing.QuotaDetails.Builder.class);
    }

    public static final int QUOTA_FIELD_NUMBER = 1;
    private int quota_ = 0;
    /**
     * <code>int32 quota = 1;</code>
     * @return The quota.
     */
    @java.lang.Override
    public int getQuota() {
      return quota_;
    }

    public static final int STATUS_FIELD_NUMBER = 2;
    private long status_ = 0L;
    /**
     * <pre>
     * contains bitmask of pk.Status
     * </pre>
     *
     * <code>uint64 status = 2;</code>
     * @return The status.
     */
    @java.lang.Override
    public long getStatus() {
      return status_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (quota_ != 0) {
        output.writeInt32(1, quota_);
      }
      if (status_ != 0L) {
        output.writeUInt64(2, status_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (quota_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, quota_);
      }
      if (status_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, status_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.passkit.grpc.Billing.QuotaDetails)) {
        return super.equals(obj);
      }
      com.passkit.grpc.Billing.QuotaDetails other = (com.passkit.grpc.Billing.QuotaDetails) obj;

      if (getQuota()
          != other.getQuota()) return false;
      if (getStatus()
          != other.getStatus()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + QUOTA_FIELD_NUMBER;
      hash = (53 * hash) + getQuota();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getStatus());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.passkit.grpc.Billing.QuotaDetails parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.passkit.grpc.Billing.QuotaDetails parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.passkit.grpc.Billing.QuotaDetails parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.passkit.grpc.Billing.QuotaDetails parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.passkit.grpc.Billing.QuotaDetails parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.passkit.grpc.Billing.QuotaDetails parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.passkit.grpc.Billing.QuotaDetails parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.passkit.grpc.Billing.QuotaDetails parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.passkit.grpc.Billing.QuotaDetails parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.passkit.grpc.Billing.QuotaDetails parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.passkit.grpc.Billing.QuotaDetails parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.passkit.grpc.Billing.QuotaDetails parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.passkit.grpc.Billing.QuotaDetails prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.QuotaDetails}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.QuotaDetails)
        com.passkit.grpc.Billing.QuotaDetailsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.passkit.grpc.Billing.internal_static_io_QuotaDetails_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.passkit.grpc.Billing.internal_static_io_QuotaDetails_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.passkit.grpc.Billing.QuotaDetails.class, com.passkit.grpc.Billing.QuotaDetails.Builder.class);
      }

      // Construct using com.passkit.grpc.Billing.QuotaDetails.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        quota_ = 0;
        status_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.passkit.grpc.Billing.internal_static_io_QuotaDetails_descriptor;
      }

      @java.lang.Override
      public com.passkit.grpc.Billing.QuotaDetails getDefaultInstanceForType() {
        return com.passkit.grpc.Billing.QuotaDetails.getDefaultInstance();
      }

      @java.lang.Override
      public com.passkit.grpc.Billing.QuotaDetails build() {
        com.passkit.grpc.Billing.QuotaDetails result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.passkit.grpc.Billing.QuotaDetails buildPartial() {
        com.passkit.grpc.Billing.QuotaDetails result = new com.passkit.grpc.Billing.QuotaDetails(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.passkit.grpc.Billing.QuotaDetails result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.quota_ = quota_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.status_ = status_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.passkit.grpc.Billing.QuotaDetails) {
          return mergeFrom((com.passkit.grpc.Billing.QuotaDetails)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.passkit.grpc.Billing.QuotaDetails other) {
        if (other == com.passkit.grpc.Billing.QuotaDetails.getDefaultInstance()) return this;
        if (other.getQuota() != 0) {
          setQuota(other.getQuota());
        }
        if (other.getStatus() != 0L) {
          setStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                quota_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                status_ = input.readUInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int quota_ ;
      /**
       * <code>int32 quota = 1;</code>
       * @return The quota.
       */
      @java.lang.Override
      public int getQuota() {
        return quota_;
      }
      /**
       * <code>int32 quota = 1;</code>
       * @param value The quota to set.
       * @return This builder for chaining.
       */
      public Builder setQuota(int value) {

        quota_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 quota = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearQuota() {
        bitField0_ = (bitField0_ & ~0x00000001);
        quota_ = 0;
        onChanged();
        return this;
      }

      private long status_ ;
      /**
       * <pre>
       * contains bitmask of pk.Status
       * </pre>
       *
       * <code>uint64 status = 2;</code>
       * @return The status.
       */
      @java.lang.Override
      public long getStatus() {
        return status_;
      }
      /**
       * <pre>
       * contains bitmask of pk.Status
       * </pre>
       *
       * <code>uint64 status = 2;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(long value) {

        status_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * contains bitmask of pk.Status
       * </pre>
       *
       * <code>uint64 status = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000002);
        status_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:io.QuotaDetails)
    }

    // @@protoc_insertion_point(class_scope:io.QuotaDetails)
    private static final com.passkit.grpc.Billing.QuotaDetails DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.passkit.grpc.Billing.QuotaDetails();
    }

    public static com.passkit.grpc.Billing.QuotaDetails getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<QuotaDetails>
        PARSER = new com.google.protobuf.AbstractParser<QuotaDetails>() {
      @java.lang.Override
      public QuotaDetails parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<QuotaDetails> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<QuotaDetails> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.passkit.grpc.Billing.QuotaDetails getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_Quota_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_Quota_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_Quota_DetailsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_Quota_DetailsEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_QuotaDetails_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_QuotaDetails_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027io/common/billing.proto\022\002io\"r\n\005Quota\022\'" +
      "\n\007details\030\001 \003(\0132\026.io.Quota.DetailsEntry\032" +
      "@\n\014DetailsEntry\022\013\n\003key\030\001 \001(\r\022\037\n\005value\030\002 " +
      "\001(\0132\020.io.QuotaDetails:\0028\001\"-\n\014QuotaDetail" +
      "s\022\r\n\005quota\030\001 \001(\005\022\016\n\006status\030\002 \001(\004BG\n\020com." +
      "passkit.grpcZ$stash.passkit.com/io/model" +
      "/sdk/go/io\252\002\014PassKit.Grpcb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_io_Quota_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_Quota_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_io_Quota_descriptor,
        new java.lang.String[] { "Details", });
    internal_static_io_Quota_DetailsEntry_descriptor =
      internal_static_io_Quota_descriptor.getNestedTypes().get(0);
    internal_static_io_Quota_DetailsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_io_Quota_DetailsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_io_QuotaDetails_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_io_QuotaDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_io_QuotaDetails_descriptor,
        new java.lang.String[] { "Quota", "Status", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
