// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: io/common/useragent.proto

package com.passkit.grpc;

public final class BrowserAgent {
  private BrowserAgent() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserAgentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.UserAgent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string raw = 1;</code>
     * @return The raw.
     */
    java.lang.String getRaw();
    /**
     * <code>string raw = 1;</code>
     * @return The bytes for raw.
     */
    com.google.protobuf.ByteString
        getRawBytes();

    /**
     * <code>string platform = 2;</code>
     * @return The platform.
     */
    java.lang.String getPlatform();
    /**
     * <code>string platform = 2;</code>
     * @return The bytes for platform.
     */
    com.google.protobuf.ByteString
        getPlatformBytes();

    /**
     * <code>string os = 3;</code>
     * @return The os.
     */
    java.lang.String getOs();
    /**
     * <code>string os = 3;</code>
     * @return The bytes for os.
     */
    com.google.protobuf.ByteString
        getOsBytes();

    /**
     * <code>string osVersion = 4;</code>
     * @return The osVersion.
     */
    java.lang.String getOsVersion();
    /**
     * <code>string osVersion = 4;</code>
     * @return The bytes for osVersion.
     */
    com.google.protobuf.ByteString
        getOsVersionBytes();

    /**
     * <code>string engine = 5;</code>
     * @return The engine.
     */
    java.lang.String getEngine();
    /**
     * <code>string engine = 5;</code>
     * @return The bytes for engine.
     */
    com.google.protobuf.ByteString
        getEngineBytes();

    /**
     * <code>string engineVersion = 6;</code>
     * @return The engineVersion.
     */
    java.lang.String getEngineVersion();
    /**
     * <code>string engineVersion = 6;</code>
     * @return The bytes for engineVersion.
     */
    com.google.protobuf.ByteString
        getEngineVersionBytes();

    /**
     * <code>string browser = 7;</code>
     * @return The browser.
     */
    java.lang.String getBrowser();
    /**
     * <code>string browser = 7;</code>
     * @return The bytes for browser.
     */
    com.google.protobuf.ByteString
        getBrowserBytes();

    /**
     * <code>string browserVersion = 8;</code>
     * @return The browserVersion.
     */
    java.lang.String getBrowserVersion();
    /**
     * <code>string browserVersion = 8;</code>
     * @return The bytes for browserVersion.
     */
    com.google.protobuf.ByteString
        getBrowserVersionBytes();

    /**
     * <code>string localization = 9;</code>
     * @return The localization.
     */
    java.lang.String getLocalization();
    /**
     * <code>string localization = 9;</code>
     * @return The bytes for localization.
     */
    com.google.protobuf.ByteString
        getLocalizationBytes();

    /**
     * <code>bool mobile = 10;</code>
     * @return The mobile.
     */
    boolean getMobile();

    /**
     * <code>bool walletCompatible = 11;</code>
     * @return The walletCompatible.
     */
    boolean getWalletCompatible();
  }
  /**
   * Protobuf type {@code io.UserAgent}
   */
  public static final class UserAgent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:io.UserAgent)
      UserAgentOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserAgent.newBuilder() to construct.
    private UserAgent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserAgent() {
      raw_ = "";
      platform_ = "";
      os_ = "";
      osVersion_ = "";
      engine_ = "";
      engineVersion_ = "";
      browser_ = "";
      browserVersion_ = "";
      localization_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UserAgent();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserAgent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              raw_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              platform_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              os_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              osVersion_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              engine_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              engineVersion_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              browser_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              browserVersion_ = s;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              localization_ = s;
              break;
            }
            case 80: {

              mobile_ = input.readBool();
              break;
            }
            case 88: {

              walletCompatible_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.passkit.grpc.BrowserAgent.internal_static_io_UserAgent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.passkit.grpc.BrowserAgent.internal_static_io_UserAgent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.passkit.grpc.BrowserAgent.UserAgent.class, com.passkit.grpc.BrowserAgent.UserAgent.Builder.class);
    }

    public static final int RAW_FIELD_NUMBER = 1;
    private volatile java.lang.Object raw_;
    /**
     * <code>string raw = 1;</code>
     * @return The raw.
     */
    @java.lang.Override
    public java.lang.String getRaw() {
      java.lang.Object ref = raw_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        raw_ = s;
        return s;
      }
    }
    /**
     * <code>string raw = 1;</code>
     * @return The bytes for raw.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRawBytes() {
      java.lang.Object ref = raw_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        raw_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PLATFORM_FIELD_NUMBER = 2;
    private volatile java.lang.Object platform_;
    /**
     * <code>string platform = 2;</code>
     * @return The platform.
     */
    @java.lang.Override
    public java.lang.String getPlatform() {
      java.lang.Object ref = platform_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        platform_ = s;
        return s;
      }
    }
    /**
     * <code>string platform = 2;</code>
     * @return The bytes for platform.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPlatformBytes() {
      java.lang.Object ref = platform_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        platform_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OS_FIELD_NUMBER = 3;
    private volatile java.lang.Object os_;
    /**
     * <code>string os = 3;</code>
     * @return The os.
     */
    @java.lang.Override
    public java.lang.String getOs() {
      java.lang.Object ref = os_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        os_ = s;
        return s;
      }
    }
    /**
     * <code>string os = 3;</code>
     * @return The bytes for os.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOsBytes() {
      java.lang.Object ref = os_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        os_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OSVERSION_FIELD_NUMBER = 4;
    private volatile java.lang.Object osVersion_;
    /**
     * <code>string osVersion = 4;</code>
     * @return The osVersion.
     */
    @java.lang.Override
    public java.lang.String getOsVersion() {
      java.lang.Object ref = osVersion_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        osVersion_ = s;
        return s;
      }
    }
    /**
     * <code>string osVersion = 4;</code>
     * @return The bytes for osVersion.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOsVersionBytes() {
      java.lang.Object ref = osVersion_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        osVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENGINE_FIELD_NUMBER = 5;
    private volatile java.lang.Object engine_;
    /**
     * <code>string engine = 5;</code>
     * @return The engine.
     */
    @java.lang.Override
    public java.lang.String getEngine() {
      java.lang.Object ref = engine_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        engine_ = s;
        return s;
      }
    }
    /**
     * <code>string engine = 5;</code>
     * @return The bytes for engine.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEngineBytes() {
      java.lang.Object ref = engine_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        engine_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENGINEVERSION_FIELD_NUMBER = 6;
    private volatile java.lang.Object engineVersion_;
    /**
     * <code>string engineVersion = 6;</code>
     * @return The engineVersion.
     */
    @java.lang.Override
    public java.lang.String getEngineVersion() {
      java.lang.Object ref = engineVersion_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        engineVersion_ = s;
        return s;
      }
    }
    /**
     * <code>string engineVersion = 6;</code>
     * @return The bytes for engineVersion.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEngineVersionBytes() {
      java.lang.Object ref = engineVersion_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        engineVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BROWSER_FIELD_NUMBER = 7;
    private volatile java.lang.Object browser_;
    /**
     * <code>string browser = 7;</code>
     * @return The browser.
     */
    @java.lang.Override
    public java.lang.String getBrowser() {
      java.lang.Object ref = browser_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        browser_ = s;
        return s;
      }
    }
    /**
     * <code>string browser = 7;</code>
     * @return The bytes for browser.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBrowserBytes() {
      java.lang.Object ref = browser_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        browser_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BROWSERVERSION_FIELD_NUMBER = 8;
    private volatile java.lang.Object browserVersion_;
    /**
     * <code>string browserVersion = 8;</code>
     * @return The browserVersion.
     */
    @java.lang.Override
    public java.lang.String getBrowserVersion() {
      java.lang.Object ref = browserVersion_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        browserVersion_ = s;
        return s;
      }
    }
    /**
     * <code>string browserVersion = 8;</code>
     * @return The bytes for browserVersion.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBrowserVersionBytes() {
      java.lang.Object ref = browserVersion_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        browserVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOCALIZATION_FIELD_NUMBER = 9;
    private volatile java.lang.Object localization_;
    /**
     * <code>string localization = 9;</code>
     * @return The localization.
     */
    @java.lang.Override
    public java.lang.String getLocalization() {
      java.lang.Object ref = localization_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        localization_ = s;
        return s;
      }
    }
    /**
     * <code>string localization = 9;</code>
     * @return The bytes for localization.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLocalizationBytes() {
      java.lang.Object ref = localization_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        localization_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MOBILE_FIELD_NUMBER = 10;
    private boolean mobile_;
    /**
     * <code>bool mobile = 10;</code>
     * @return The mobile.
     */
    @java.lang.Override
    public boolean getMobile() {
      return mobile_;
    }

    public static final int WALLETCOMPATIBLE_FIELD_NUMBER = 11;
    private boolean walletCompatible_;
    /**
     * <code>bool walletCompatible = 11;</code>
     * @return The walletCompatible.
     */
    @java.lang.Override
    public boolean getWalletCompatible() {
      return walletCompatible_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(raw_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, raw_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(platform_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, platform_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(os_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, os_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(osVersion_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, osVersion_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(engine_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, engine_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(engineVersion_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, engineVersion_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(browser_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, browser_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(browserVersion_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, browserVersion_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(localization_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, localization_);
      }
      if (mobile_ != false) {
        output.writeBool(10, mobile_);
      }
      if (walletCompatible_ != false) {
        output.writeBool(11, walletCompatible_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(raw_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, raw_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(platform_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, platform_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(os_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, os_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(osVersion_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, osVersion_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(engine_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, engine_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(engineVersion_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, engineVersion_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(browser_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, browser_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(browserVersion_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, browserVersion_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(localization_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, localization_);
      }
      if (mobile_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(10, mobile_);
      }
      if (walletCompatible_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(11, walletCompatible_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.passkit.grpc.BrowserAgent.UserAgent)) {
        return super.equals(obj);
      }
      com.passkit.grpc.BrowserAgent.UserAgent other = (com.passkit.grpc.BrowserAgent.UserAgent) obj;

      if (!getRaw()
          .equals(other.getRaw())) return false;
      if (!getPlatform()
          .equals(other.getPlatform())) return false;
      if (!getOs()
          .equals(other.getOs())) return false;
      if (!getOsVersion()
          .equals(other.getOsVersion())) return false;
      if (!getEngine()
          .equals(other.getEngine())) return false;
      if (!getEngineVersion()
          .equals(other.getEngineVersion())) return false;
      if (!getBrowser()
          .equals(other.getBrowser())) return false;
      if (!getBrowserVersion()
          .equals(other.getBrowserVersion())) return false;
      if (!getLocalization()
          .equals(other.getLocalization())) return false;
      if (getMobile()
          != other.getMobile()) return false;
      if (getWalletCompatible()
          != other.getWalletCompatible()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RAW_FIELD_NUMBER;
      hash = (53 * hash) + getRaw().hashCode();
      hash = (37 * hash) + PLATFORM_FIELD_NUMBER;
      hash = (53 * hash) + getPlatform().hashCode();
      hash = (37 * hash) + OS_FIELD_NUMBER;
      hash = (53 * hash) + getOs().hashCode();
      hash = (37 * hash) + OSVERSION_FIELD_NUMBER;
      hash = (53 * hash) + getOsVersion().hashCode();
      hash = (37 * hash) + ENGINE_FIELD_NUMBER;
      hash = (53 * hash) + getEngine().hashCode();
      hash = (37 * hash) + ENGINEVERSION_FIELD_NUMBER;
      hash = (53 * hash) + getEngineVersion().hashCode();
      hash = (37 * hash) + BROWSER_FIELD_NUMBER;
      hash = (53 * hash) + getBrowser().hashCode();
      hash = (37 * hash) + BROWSERVERSION_FIELD_NUMBER;
      hash = (53 * hash) + getBrowserVersion().hashCode();
      hash = (37 * hash) + LOCALIZATION_FIELD_NUMBER;
      hash = (53 * hash) + getLocalization().hashCode();
      hash = (37 * hash) + MOBILE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getMobile());
      hash = (37 * hash) + WALLETCOMPATIBLE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getWalletCompatible());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.passkit.grpc.BrowserAgent.UserAgent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.passkit.grpc.BrowserAgent.UserAgent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.passkit.grpc.BrowserAgent.UserAgent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.passkit.grpc.BrowserAgent.UserAgent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.passkit.grpc.BrowserAgent.UserAgent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.passkit.grpc.BrowserAgent.UserAgent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.passkit.grpc.BrowserAgent.UserAgent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.passkit.grpc.BrowserAgent.UserAgent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.passkit.grpc.BrowserAgent.UserAgent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.passkit.grpc.BrowserAgent.UserAgent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.passkit.grpc.BrowserAgent.UserAgent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.passkit.grpc.BrowserAgent.UserAgent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.passkit.grpc.BrowserAgent.UserAgent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.UserAgent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.UserAgent)
        com.passkit.grpc.BrowserAgent.UserAgentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.passkit.grpc.BrowserAgent.internal_static_io_UserAgent_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.passkit.grpc.BrowserAgent.internal_static_io_UserAgent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.passkit.grpc.BrowserAgent.UserAgent.class, com.passkit.grpc.BrowserAgent.UserAgent.Builder.class);
      }

      // Construct using com.passkit.grpc.BrowserAgent.UserAgent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        raw_ = "";

        platform_ = "";

        os_ = "";

        osVersion_ = "";

        engine_ = "";

        engineVersion_ = "";

        browser_ = "";

        browserVersion_ = "";

        localization_ = "";

        mobile_ = false;

        walletCompatible_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.passkit.grpc.BrowserAgent.internal_static_io_UserAgent_descriptor;
      }

      @java.lang.Override
      public com.passkit.grpc.BrowserAgent.UserAgent getDefaultInstanceForType() {
        return com.passkit.grpc.BrowserAgent.UserAgent.getDefaultInstance();
      }

      @java.lang.Override
      public com.passkit.grpc.BrowserAgent.UserAgent build() {
        com.passkit.grpc.BrowserAgent.UserAgent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.passkit.grpc.BrowserAgent.UserAgent buildPartial() {
        com.passkit.grpc.BrowserAgent.UserAgent result = new com.passkit.grpc.BrowserAgent.UserAgent(this);
        result.raw_ = raw_;
        result.platform_ = platform_;
        result.os_ = os_;
        result.osVersion_ = osVersion_;
        result.engine_ = engine_;
        result.engineVersion_ = engineVersion_;
        result.browser_ = browser_;
        result.browserVersion_ = browserVersion_;
        result.localization_ = localization_;
        result.mobile_ = mobile_;
        result.walletCompatible_ = walletCompatible_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.passkit.grpc.BrowserAgent.UserAgent) {
          return mergeFrom((com.passkit.grpc.BrowserAgent.UserAgent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.passkit.grpc.BrowserAgent.UserAgent other) {
        if (other == com.passkit.grpc.BrowserAgent.UserAgent.getDefaultInstance()) return this;
        if (!other.getRaw().isEmpty()) {
          raw_ = other.raw_;
          onChanged();
        }
        if (!other.getPlatform().isEmpty()) {
          platform_ = other.platform_;
          onChanged();
        }
        if (!other.getOs().isEmpty()) {
          os_ = other.os_;
          onChanged();
        }
        if (!other.getOsVersion().isEmpty()) {
          osVersion_ = other.osVersion_;
          onChanged();
        }
        if (!other.getEngine().isEmpty()) {
          engine_ = other.engine_;
          onChanged();
        }
        if (!other.getEngineVersion().isEmpty()) {
          engineVersion_ = other.engineVersion_;
          onChanged();
        }
        if (!other.getBrowser().isEmpty()) {
          browser_ = other.browser_;
          onChanged();
        }
        if (!other.getBrowserVersion().isEmpty()) {
          browserVersion_ = other.browserVersion_;
          onChanged();
        }
        if (!other.getLocalization().isEmpty()) {
          localization_ = other.localization_;
          onChanged();
        }
        if (other.getMobile() != false) {
          setMobile(other.getMobile());
        }
        if (other.getWalletCompatible() != false) {
          setWalletCompatible(other.getWalletCompatible());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.passkit.grpc.BrowserAgent.UserAgent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.passkit.grpc.BrowserAgent.UserAgent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object raw_ = "";
      /**
       * <code>string raw = 1;</code>
       * @return The raw.
       */
      public java.lang.String getRaw() {
        java.lang.Object ref = raw_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          raw_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string raw = 1;</code>
       * @return The bytes for raw.
       */
      public com.google.protobuf.ByteString
          getRawBytes() {
        java.lang.Object ref = raw_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          raw_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string raw = 1;</code>
       * @param value The raw to set.
       * @return This builder for chaining.
       */
      public Builder setRaw(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        raw_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string raw = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRaw() {
        
        raw_ = getDefaultInstance().getRaw();
        onChanged();
        return this;
      }
      /**
       * <code>string raw = 1;</code>
       * @param value The bytes for raw to set.
       * @return This builder for chaining.
       */
      public Builder setRawBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        raw_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object platform_ = "";
      /**
       * <code>string platform = 2;</code>
       * @return The platform.
       */
      public java.lang.String getPlatform() {
        java.lang.Object ref = platform_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          platform_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string platform = 2;</code>
       * @return The bytes for platform.
       */
      public com.google.protobuf.ByteString
          getPlatformBytes() {
        java.lang.Object ref = platform_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          platform_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string platform = 2;</code>
       * @param value The platform to set.
       * @return This builder for chaining.
       */
      public Builder setPlatform(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        platform_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string platform = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPlatform() {
        
        platform_ = getDefaultInstance().getPlatform();
        onChanged();
        return this;
      }
      /**
       * <code>string platform = 2;</code>
       * @param value The bytes for platform to set.
       * @return This builder for chaining.
       */
      public Builder setPlatformBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        platform_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object os_ = "";
      /**
       * <code>string os = 3;</code>
       * @return The os.
       */
      public java.lang.String getOs() {
        java.lang.Object ref = os_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          os_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string os = 3;</code>
       * @return The bytes for os.
       */
      public com.google.protobuf.ByteString
          getOsBytes() {
        java.lang.Object ref = os_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          os_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string os = 3;</code>
       * @param value The os to set.
       * @return This builder for chaining.
       */
      public Builder setOs(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        os_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string os = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearOs() {
        
        os_ = getDefaultInstance().getOs();
        onChanged();
        return this;
      }
      /**
       * <code>string os = 3;</code>
       * @param value The bytes for os to set.
       * @return This builder for chaining.
       */
      public Builder setOsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        os_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object osVersion_ = "";
      /**
       * <code>string osVersion = 4;</code>
       * @return The osVersion.
       */
      public java.lang.String getOsVersion() {
        java.lang.Object ref = osVersion_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          osVersion_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string osVersion = 4;</code>
       * @return The bytes for osVersion.
       */
      public com.google.protobuf.ByteString
          getOsVersionBytes() {
        java.lang.Object ref = osVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          osVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string osVersion = 4;</code>
       * @param value The osVersion to set.
       * @return This builder for chaining.
       */
      public Builder setOsVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        osVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string osVersion = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearOsVersion() {
        
        osVersion_ = getDefaultInstance().getOsVersion();
        onChanged();
        return this;
      }
      /**
       * <code>string osVersion = 4;</code>
       * @param value The bytes for osVersion to set.
       * @return This builder for chaining.
       */
      public Builder setOsVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        osVersion_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object engine_ = "";
      /**
       * <code>string engine = 5;</code>
       * @return The engine.
       */
      public java.lang.String getEngine() {
        java.lang.Object ref = engine_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          engine_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string engine = 5;</code>
       * @return The bytes for engine.
       */
      public com.google.protobuf.ByteString
          getEngineBytes() {
        java.lang.Object ref = engine_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          engine_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string engine = 5;</code>
       * @param value The engine to set.
       * @return This builder for chaining.
       */
      public Builder setEngine(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        engine_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string engine = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearEngine() {
        
        engine_ = getDefaultInstance().getEngine();
        onChanged();
        return this;
      }
      /**
       * <code>string engine = 5;</code>
       * @param value The bytes for engine to set.
       * @return This builder for chaining.
       */
      public Builder setEngineBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        engine_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object engineVersion_ = "";
      /**
       * <code>string engineVersion = 6;</code>
       * @return The engineVersion.
       */
      public java.lang.String getEngineVersion() {
        java.lang.Object ref = engineVersion_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          engineVersion_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string engineVersion = 6;</code>
       * @return The bytes for engineVersion.
       */
      public com.google.protobuf.ByteString
          getEngineVersionBytes() {
        java.lang.Object ref = engineVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          engineVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string engineVersion = 6;</code>
       * @param value The engineVersion to set.
       * @return This builder for chaining.
       */
      public Builder setEngineVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        engineVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string engineVersion = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearEngineVersion() {
        
        engineVersion_ = getDefaultInstance().getEngineVersion();
        onChanged();
        return this;
      }
      /**
       * <code>string engineVersion = 6;</code>
       * @param value The bytes for engineVersion to set.
       * @return This builder for chaining.
       */
      public Builder setEngineVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        engineVersion_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object browser_ = "";
      /**
       * <code>string browser = 7;</code>
       * @return The browser.
       */
      public java.lang.String getBrowser() {
        java.lang.Object ref = browser_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          browser_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string browser = 7;</code>
       * @return The bytes for browser.
       */
      public com.google.protobuf.ByteString
          getBrowserBytes() {
        java.lang.Object ref = browser_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          browser_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string browser = 7;</code>
       * @param value The browser to set.
       * @return This builder for chaining.
       */
      public Builder setBrowser(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        browser_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string browser = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearBrowser() {
        
        browser_ = getDefaultInstance().getBrowser();
        onChanged();
        return this;
      }
      /**
       * <code>string browser = 7;</code>
       * @param value The bytes for browser to set.
       * @return This builder for chaining.
       */
      public Builder setBrowserBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        browser_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object browserVersion_ = "";
      /**
       * <code>string browserVersion = 8;</code>
       * @return The browserVersion.
       */
      public java.lang.String getBrowserVersion() {
        java.lang.Object ref = browserVersion_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          browserVersion_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string browserVersion = 8;</code>
       * @return The bytes for browserVersion.
       */
      public com.google.protobuf.ByteString
          getBrowserVersionBytes() {
        java.lang.Object ref = browserVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          browserVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string browserVersion = 8;</code>
       * @param value The browserVersion to set.
       * @return This builder for chaining.
       */
      public Builder setBrowserVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        browserVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string browserVersion = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearBrowserVersion() {
        
        browserVersion_ = getDefaultInstance().getBrowserVersion();
        onChanged();
        return this;
      }
      /**
       * <code>string browserVersion = 8;</code>
       * @param value The bytes for browserVersion to set.
       * @return This builder for chaining.
       */
      public Builder setBrowserVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        browserVersion_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object localization_ = "";
      /**
       * <code>string localization = 9;</code>
       * @return The localization.
       */
      public java.lang.String getLocalization() {
        java.lang.Object ref = localization_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          localization_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string localization = 9;</code>
       * @return The bytes for localization.
       */
      public com.google.protobuf.ByteString
          getLocalizationBytes() {
        java.lang.Object ref = localization_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          localization_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string localization = 9;</code>
       * @param value The localization to set.
       * @return This builder for chaining.
       */
      public Builder setLocalization(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        localization_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string localization = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearLocalization() {
        
        localization_ = getDefaultInstance().getLocalization();
        onChanged();
        return this;
      }
      /**
       * <code>string localization = 9;</code>
       * @param value The bytes for localization to set.
       * @return This builder for chaining.
       */
      public Builder setLocalizationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        localization_ = value;
        onChanged();
        return this;
      }

      private boolean mobile_ ;
      /**
       * <code>bool mobile = 10;</code>
       * @return The mobile.
       */
      @java.lang.Override
      public boolean getMobile() {
        return mobile_;
      }
      /**
       * <code>bool mobile = 10;</code>
       * @param value The mobile to set.
       * @return This builder for chaining.
       */
      public Builder setMobile(boolean value) {
        
        mobile_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool mobile = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearMobile() {
        
        mobile_ = false;
        onChanged();
        return this;
      }

      private boolean walletCompatible_ ;
      /**
       * <code>bool walletCompatible = 11;</code>
       * @return The walletCompatible.
       */
      @java.lang.Override
      public boolean getWalletCompatible() {
        return walletCompatible_;
      }
      /**
       * <code>bool walletCompatible = 11;</code>
       * @param value The walletCompatible to set.
       * @return This builder for chaining.
       */
      public Builder setWalletCompatible(boolean value) {
        
        walletCompatible_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool walletCompatible = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearWalletCompatible() {
        
        walletCompatible_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:io.UserAgent)
    }

    // @@protoc_insertion_point(class_scope:io.UserAgent)
    private static final com.passkit.grpc.BrowserAgent.UserAgent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.passkit.grpc.BrowserAgent.UserAgent();
    }

    public static com.passkit.grpc.BrowserAgent.UserAgent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserAgent>
        PARSER = new com.google.protobuf.AbstractParser<UserAgent>() {
      @java.lang.Override
      public UserAgent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserAgent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserAgent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserAgent> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.passkit.grpc.BrowserAgent.UserAgent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_UserAgent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_UserAgent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031io/common/useragent.proto\022\002io\"\331\001\n\tUser" +
      "Agent\022\013\n\003raw\030\001 \001(\t\022\020\n\010platform\030\002 \001(\t\022\n\n\002" +
      "os\030\003 \001(\t\022\021\n\tosVersion\030\004 \001(\t\022\016\n\006engine\030\005 " +
      "\001(\t\022\025\n\rengineVersion\030\006 \001(\t\022\017\n\007browser\030\007 " +
      "\001(\t\022\026\n\016browserVersion\030\010 \001(\t\022\024\n\014localizat" +
      "ion\030\t \001(\t\022\016\n\006mobile\030\n \001(\010\022\030\n\020walletCompa" +
      "tible\030\013 \001(\010BU\n\020com.passkit.grpcB\014Browser" +
      "AgentZ$stash.passkit.com/io/model/sdk/go" +
      "/io\252\002\014PassKit.Grpcb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_io_UserAgent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_UserAgent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_UserAgent_descriptor,
        new java.lang.String[] { "Raw", "Platform", "Os", "OsVersion", "Engine", "EngineVersion", "Browser", "BrowserVersion", "Localization", "Mobile", "WalletCompatible", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
