// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: io/common/featured_actions.proto
// Protobuf Java Version: 4.31.1

package com.passkit.grpc;

@com.google.protobuf.Generated
public final class FeaturedActions {
  private FeaturedActions() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      FeaturedActions.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * Supported Apple Wallet featured action types.
   * </pre>
   *
   * Protobuf enum {@code io.FeaturedActionType}
   */
  public enum FeaturedActionType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>FEATURED_ACTION_DO_NOT_USE = 0;</code>
     */
    FEATURED_ACTION_DO_NOT_USE(0),
    /**
     * <pre>
     * Opens a schedule or itinerary view.
     * </pre>
     *
     * <code>VIEW_SCHEDULE = 1;</code>
     */
    VIEW_SCHEDULE(1),
    /**
     * <pre>
     * Opens video content such as a trailer.
     * </pre>
     *
     * <code>WATCH_TRAILER = 2;</code>
     */
    WATCH_TRAILER(2),
    /**
     * <pre>
     * Opens music content such as a playlist or album.
     * </pre>
     *
     * <code>LISTEN_TO_MUSIC = 3;</code>
     */
    LISTEN_TO_MUSIC(3),
    /**
     * <pre>
     * Opens a place, map, or venue destination.
     * </pre>
     *
     * <code>PLACE = 4;</code>
     */
    PLACE(4),
    /**
     * <pre>
     * Opens a commerce or merchandising experience.
     * </pre>
     *
     * <code>SHOP = 5;</code>
     */
    SHOP(5),
    /**
     * <pre>
     * Opens a flow to add stored value or balance.
     * </pre>
     *
     * <code>ADD_TO_BALANCE = 6;</code>
     */
    ADD_TO_BALANCE(6),
    /**
     * <pre>
     * Starts a phone call.
     * </pre>
     *
     * <code>TELEPHONE = 7;</code>
     */
    TELEPHONE(7),
    /**
     * <pre>
     * Opens offers, rewards, or loyalty benefits.
     * </pre>
     *
     * <code>VIEW_OFFERS_REWARDS = 8;</code>
     */
    VIEW_OFFERS_REWARDS(8),
    /**
     * <pre>
     * Opens accommodation booking or management.
     * </pre>
     *
     * <code>BOOK_STAY = 9;</code>
     */
    BOOK_STAY(9),
    /**
     * <pre>
     * Opens flight booking or management.
     * </pre>
     *
     * <code>BOOK_FLIGHT = 10;</code>
     */
    BOOK_FLIGHT(10),
    /**
     * <pre>
     * Opens car booking or management.
     * </pre>
     *
     * <code>BOOK_CAR = 11;</code>
     */
    BOOK_CAR(11),
    /**
     * <pre>
     * Opens appointment booking or management.
     * </pre>
     *
     * <code>BOOK_APPOINTMENT = 12;</code>
     */
    BOOK_APPOINTMENT(12),
    /**
     * <pre>
     * Opens membership benefits or entitlement details.
     * </pre>
     *
     * <code>MEMBERSHIP_BENEFITS = 13;</code>
     */
    MEMBERSHIP_BENEFITS(13),
    /**
     * <pre>
     * Opens a link to place an order.
     * </pre>
     *
     * <code>ORDER = 14;</code>
     */
    ORDER(14),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        FeaturedActionType.class.getName());
    }
    /**
     * <code>FEATURED_ACTION_DO_NOT_USE = 0;</code>
     */
    public static final int FEATURED_ACTION_DO_NOT_USE_VALUE = 0;
    /**
     * <pre>
     * Opens a schedule or itinerary view.
     * </pre>
     *
     * <code>VIEW_SCHEDULE = 1;</code>
     */
    public static final int VIEW_SCHEDULE_VALUE = 1;
    /**
     * <pre>
     * Opens video content such as a trailer.
     * </pre>
     *
     * <code>WATCH_TRAILER = 2;</code>
     */
    public static final int WATCH_TRAILER_VALUE = 2;
    /**
     * <pre>
     * Opens music content such as a playlist or album.
     * </pre>
     *
     * <code>LISTEN_TO_MUSIC = 3;</code>
     */
    public static final int LISTEN_TO_MUSIC_VALUE = 3;
    /**
     * <pre>
     * Opens a place, map, or venue destination.
     * </pre>
     *
     * <code>PLACE = 4;</code>
     */
    public static final int PLACE_VALUE = 4;
    /**
     * <pre>
     * Opens a commerce or merchandising experience.
     * </pre>
     *
     * <code>SHOP = 5;</code>
     */
    public static final int SHOP_VALUE = 5;
    /**
     * <pre>
     * Opens a flow to add stored value or balance.
     * </pre>
     *
     * <code>ADD_TO_BALANCE = 6;</code>
     */
    public static final int ADD_TO_BALANCE_VALUE = 6;
    /**
     * <pre>
     * Starts a phone call.
     * </pre>
     *
     * <code>TELEPHONE = 7;</code>
     */
    public static final int TELEPHONE_VALUE = 7;
    /**
     * <pre>
     * Opens offers, rewards, or loyalty benefits.
     * </pre>
     *
     * <code>VIEW_OFFERS_REWARDS = 8;</code>
     */
    public static final int VIEW_OFFERS_REWARDS_VALUE = 8;
    /**
     * <pre>
     * Opens accommodation booking or management.
     * </pre>
     *
     * <code>BOOK_STAY = 9;</code>
     */
    public static final int BOOK_STAY_VALUE = 9;
    /**
     * <pre>
     * Opens flight booking or management.
     * </pre>
     *
     * <code>BOOK_FLIGHT = 10;</code>
     */
    public static final int BOOK_FLIGHT_VALUE = 10;
    /**
     * <pre>
     * Opens car booking or management.
     * </pre>
     *
     * <code>BOOK_CAR = 11;</code>
     */
    public static final int BOOK_CAR_VALUE = 11;
    /**
     * <pre>
     * Opens appointment booking or management.
     * </pre>
     *
     * <code>BOOK_APPOINTMENT = 12;</code>
     */
    public static final int BOOK_APPOINTMENT_VALUE = 12;
    /**
     * <pre>
     * Opens membership benefits or entitlement details.
     * </pre>
     *
     * <code>MEMBERSHIP_BENEFITS = 13;</code>
     */
    public static final int MEMBERSHIP_BENEFITS_VALUE = 13;
    /**
     * <pre>
     * Opens a link to place an order.
     * </pre>
     *
     * <code>ORDER = 14;</code>
     */
    public static final int ORDER_VALUE = 14;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static FeaturedActionType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static FeaturedActionType forNumber(int value) {
      switch (value) {
        case 0: return FEATURED_ACTION_DO_NOT_USE;
        case 1: return VIEW_SCHEDULE;
        case 2: return WATCH_TRAILER;
        case 3: return LISTEN_TO_MUSIC;
        case 4: return PLACE;
        case 5: return SHOP;
        case 6: return ADD_TO_BALANCE;
        case 7: return TELEPHONE;
        case 8: return VIEW_OFFERS_REWARDS;
        case 9: return BOOK_STAY;
        case 10: return BOOK_FLIGHT;
        case 11: return BOOK_CAR;
        case 12: return BOOK_APPOINTMENT;
        case 13: return MEMBERSHIP_BENEFITS;
        case 14: return ORDER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<FeaturedActionType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        FeaturedActionType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<FeaturedActionType>() {
            public FeaturedActionType findValueByNumber(int number) {
              return FeaturedActionType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.passkit.grpc.FeaturedActions.getDescriptor().getEnumTypes().get(0);
    }

    private static final FeaturedActionType[] VALUES = values();

    public static FeaturedActionType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private FeaturedActionType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:io.FeaturedActionType)
  }

  public interface FeaturedActionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.FeaturedAction)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Stable identifier for the action.
     * </pre>
     *
     * <code>string identifier = 1;</code>
     * @return The identifier.
     */
    java.lang.String getIdentifier();
    /**
     * <pre>
     * Stable identifier for the action.
     * </pre>
     *
     * <code>string identifier = 1;</code>
     * @return The bytes for identifier.
     */
    com.google.protobuf.ByteString
        getIdentifierBytes();

    /**
     * <pre>
     * The system action type to render in Apple Wallet.
     * </pre>
     *
     * <code>.io.FeaturedActionType type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <pre>
     * The system action type to render in Apple Wallet.
     * </pre>
     *
     * <code>.io.FeaturedActionType type = 2;</code>
     * @return The type.
     */
    com.passkit.grpc.FeaturedActions.FeaturedActionType getType();

    /**
     * <pre>
     * Optional URL or deep link opened when the action is selected.
     * </pre>
     *
     * <code>string url = 3;</code>
     * @return The url.
     */
    java.lang.String getUrl();
    /**
     * <pre>
     * Optional URL or deep link opened when the action is selected.
     * </pre>
     *
     * <code>string url = 3;</code>
     * @return The bytes for url.
     */
    com.google.protobuf.ByteString
        getUrlBytes();
  }
  /**
   * <pre>
   * A single Apple Wallet featured action. Apple currently supports up to two
   * actions per pass, ordered by priority in the list.
   * </pre>
   *
   * Protobuf type {@code io.FeaturedAction}
   */
  public static final class FeaturedAction extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:io.FeaturedAction)
      FeaturedActionOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        FeaturedAction.class.getName());
    }
    // Use FeaturedAction.newBuilder() to construct.
    private FeaturedAction(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private FeaturedAction() {
      identifier_ = "";
      type_ = 0;
      url_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.passkit.grpc.FeaturedActions.internal_static_io_FeaturedAction_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.passkit.grpc.FeaturedActions.internal_static_io_FeaturedAction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.passkit.grpc.FeaturedActions.FeaturedAction.class, com.passkit.grpc.FeaturedActions.FeaturedAction.Builder.class);
    }

    public static final int IDENTIFIER_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object identifier_ = "";
    /**
     * <pre>
     * Stable identifier for the action.
     * </pre>
     *
     * <code>string identifier = 1;</code>
     * @return The identifier.
     */
    @java.lang.Override
    public java.lang.String getIdentifier() {
      java.lang.Object ref = identifier_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        identifier_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Stable identifier for the action.
     * </pre>
     *
     * <code>string identifier = 1;</code>
     * @return The bytes for identifier.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdentifierBytes() {
      java.lang.Object ref = identifier_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        identifier_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_ = 0;
    /**
     * <pre>
     * The system action type to render in Apple Wallet.
     * </pre>
     *
     * <code>.io.FeaturedActionType type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     * The system action type to render in Apple Wallet.
     * </pre>
     *
     * <code>.io.FeaturedActionType type = 2;</code>
     * @return The type.
     */
    @java.lang.Override public com.passkit.grpc.FeaturedActions.FeaturedActionType getType() {
      com.passkit.grpc.FeaturedActions.FeaturedActionType result = com.passkit.grpc.FeaturedActions.FeaturedActionType.forNumber(type_);
      return result == null ? com.passkit.grpc.FeaturedActions.FeaturedActionType.UNRECOGNIZED : result;
    }

    public static final int URL_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object url_ = "";
    /**
     * <pre>
     * Optional URL or deep link opened when the action is selected.
     * </pre>
     *
     * <code>string url = 3;</code>
     * @return The url.
     */
    @java.lang.Override
    public java.lang.String getUrl() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        url_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Optional URL or deep link opened when the action is selected.
     * </pre>
     *
     * <code>string url = 3;</code>
     * @return The bytes for url.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(identifier_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, identifier_);
      }
      if (type_ != com.passkit.grpc.FeaturedActions.FeaturedActionType.FEATURED_ACTION_DO_NOT_USE.getNumber()) {
        output.writeEnum(2, type_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(url_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, url_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(identifier_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, identifier_);
      }
      if (type_ != com.passkit.grpc.FeaturedActions.FeaturedActionType.FEATURED_ACTION_DO_NOT_USE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(url_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, url_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.passkit.grpc.FeaturedActions.FeaturedAction)) {
        return super.equals(obj);
      }
      com.passkit.grpc.FeaturedActions.FeaturedAction other = (com.passkit.grpc.FeaturedActions.FeaturedAction) obj;

      if (!getIdentifier()
          .equals(other.getIdentifier())) return false;
      if (type_ != other.type_) return false;
      if (!getUrl()
          .equals(other.getUrl())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IDENTIFIER_FIELD_NUMBER;
      hash = (53 * hash) + getIdentifier().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + URL_FIELD_NUMBER;
      hash = (53 * hash) + getUrl().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.passkit.grpc.FeaturedActions.FeaturedAction parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.passkit.grpc.FeaturedActions.FeaturedAction parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.passkit.grpc.FeaturedActions.FeaturedAction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.passkit.grpc.FeaturedActions.FeaturedAction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.passkit.grpc.FeaturedActions.FeaturedAction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.passkit.grpc.FeaturedActions.FeaturedAction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.passkit.grpc.FeaturedActions.FeaturedAction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.passkit.grpc.FeaturedActions.FeaturedAction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.passkit.grpc.FeaturedActions.FeaturedAction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.passkit.grpc.FeaturedActions.FeaturedAction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.passkit.grpc.FeaturedActions.FeaturedAction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.passkit.grpc.FeaturedActions.FeaturedAction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.passkit.grpc.FeaturedActions.FeaturedAction prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * A single Apple Wallet featured action. Apple currently supports up to two
     * actions per pass, ordered by priority in the list.
     * </pre>
     *
     * Protobuf type {@code io.FeaturedAction}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.FeaturedAction)
        com.passkit.grpc.FeaturedActions.FeaturedActionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.passkit.grpc.FeaturedActions.internal_static_io_FeaturedAction_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.passkit.grpc.FeaturedActions.internal_static_io_FeaturedAction_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.passkit.grpc.FeaturedActions.FeaturedAction.class, com.passkit.grpc.FeaturedActions.FeaturedAction.Builder.class);
      }

      // Construct using com.passkit.grpc.FeaturedActions.FeaturedAction.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        identifier_ = "";
        type_ = 0;
        url_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.passkit.grpc.FeaturedActions.internal_static_io_FeaturedAction_descriptor;
      }

      @java.lang.Override
      public com.passkit.grpc.FeaturedActions.FeaturedAction getDefaultInstanceForType() {
        return com.passkit.grpc.FeaturedActions.FeaturedAction.getDefaultInstance();
      }

      @java.lang.Override
      public com.passkit.grpc.FeaturedActions.FeaturedAction build() {
        com.passkit.grpc.FeaturedActions.FeaturedAction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.passkit.grpc.FeaturedActions.FeaturedAction buildPartial() {
        com.passkit.grpc.FeaturedActions.FeaturedAction result = new com.passkit.grpc.FeaturedActions.FeaturedAction(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.passkit.grpc.FeaturedActions.FeaturedAction result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.identifier_ = identifier_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.type_ = type_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.url_ = url_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.passkit.grpc.FeaturedActions.FeaturedAction) {
          return mergeFrom((com.passkit.grpc.FeaturedActions.FeaturedAction)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.passkit.grpc.FeaturedActions.FeaturedAction other) {
        if (other == com.passkit.grpc.FeaturedActions.FeaturedAction.getDefaultInstance()) return this;
        if (!other.getIdentifier().isEmpty()) {
          identifier_ = other.identifier_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (!other.getUrl().isEmpty()) {
          url_ = other.url_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                identifier_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                type_ = input.readEnum();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                url_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object identifier_ = "";
      /**
       * <pre>
       * Stable identifier for the action.
       * </pre>
       *
       * <code>string identifier = 1;</code>
       * @return The identifier.
       */
      public java.lang.String getIdentifier() {
        java.lang.Object ref = identifier_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          identifier_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Stable identifier for the action.
       * </pre>
       *
       * <code>string identifier = 1;</code>
       * @return The bytes for identifier.
       */
      public com.google.protobuf.ByteString
          getIdentifierBytes() {
        java.lang.Object ref = identifier_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          identifier_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Stable identifier for the action.
       * </pre>
       *
       * <code>string identifier = 1;</code>
       * @param value The identifier to set.
       * @return This builder for chaining.
       */
      public Builder setIdentifier(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        identifier_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Stable identifier for the action.
       * </pre>
       *
       * <code>string identifier = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIdentifier() {
        identifier_ = getDefaultInstance().getIdentifier();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Stable identifier for the action.
       * </pre>
       *
       * <code>string identifier = 1;</code>
       * @param value The bytes for identifier to set.
       * @return This builder for chaining.
       */
      public Builder setIdentifierBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        identifier_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <pre>
       * The system action type to render in Apple Wallet.
       * </pre>
       *
       * <code>.io.FeaturedActionType type = 2;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <pre>
       * The system action type to render in Apple Wallet.
       * </pre>
       *
       * <code>.io.FeaturedActionType type = 2;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The system action type to render in Apple Wallet.
       * </pre>
       *
       * <code>.io.FeaturedActionType type = 2;</code>
       * @return The type.
       */
      @java.lang.Override
      public com.passkit.grpc.FeaturedActions.FeaturedActionType getType() {
        com.passkit.grpc.FeaturedActions.FeaturedActionType result = com.passkit.grpc.FeaturedActions.FeaturedActionType.forNumber(type_);
        return result == null ? com.passkit.grpc.FeaturedActions.FeaturedActionType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * The system action type to render in Apple Wallet.
       * </pre>
       *
       * <code>.io.FeaturedActionType type = 2;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(com.passkit.grpc.FeaturedActions.FeaturedActionType value) {
        if (value == null) { throw new NullPointerException(); }
        bitField0_ |= 0x00000002;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The system action type to render in Apple Wallet.
       * </pre>
       *
       * <code>.io.FeaturedActionType type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object url_ = "";
      /**
       * <pre>
       * Optional URL or deep link opened when the action is selected.
       * </pre>
       *
       * <code>string url = 3;</code>
       * @return The url.
       */
      public java.lang.String getUrl() {
        java.lang.Object ref = url_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          url_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Optional URL or deep link opened when the action is selected.
       * </pre>
       *
       * <code>string url = 3;</code>
       * @return The bytes for url.
       */
      public com.google.protobuf.ByteString
          getUrlBytes() {
        java.lang.Object ref = url_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          url_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Optional URL or deep link opened when the action is selected.
       * </pre>
       *
       * <code>string url = 3;</code>
       * @param value The url to set.
       * @return This builder for chaining.
       */
      public Builder setUrl(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        url_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Optional URL or deep link opened when the action is selected.
       * </pre>
       *
       * <code>string url = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearUrl() {
        url_ = getDefaultInstance().getUrl();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Optional URL or deep link opened when the action is selected.
       * </pre>
       *
       * <code>string url = 3;</code>
       * @param value The bytes for url to set.
       * @return This builder for chaining.
       */
      public Builder setUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        url_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:io.FeaturedAction)
    }

    // @@protoc_insertion_point(class_scope:io.FeaturedAction)
    private static final com.passkit.grpc.FeaturedActions.FeaturedAction DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.passkit.grpc.FeaturedActions.FeaturedAction();
    }

    public static com.passkit.grpc.FeaturedActions.FeaturedAction getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FeaturedAction>
        PARSER = new com.google.protobuf.AbstractParser<FeaturedAction>() {
      @java.lang.Override
      public FeaturedAction parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<FeaturedAction> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FeaturedAction> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.passkit.grpc.FeaturedActions.FeaturedAction getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_FeaturedAction_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_FeaturedAction_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n io/common/featured_actions.proto\022\002io\"W" +
      "\n\016FeaturedAction\022\022\n\nidentifier\030\001 \001(\t\022$\n\004" +
      "type\030\002 \001(\0162\026.io.FeaturedActionType\022\013\n\003ur" +
      "l\030\003 \001(\t*\250\002\n\022FeaturedActionType\022\036\n\032FEATUR" +
      "ED_ACTION_DO_NOT_USE\020\000\022\021\n\rVIEW_SCHEDULE\020" +
      "\001\022\021\n\rWATCH_TRAILER\020\002\022\023\n\017LISTEN_TO_MUSIC\020" +
      "\003\022\t\n\005PLACE\020\004\022\010\n\004SHOP\020\005\022\022\n\016ADD_TO_BALANCE" +
      "\020\006\022\r\n\tTELEPHONE\020\007\022\027\n\023VIEW_OFFERS_REWARDS" +
      "\020\010\022\r\n\tBOOK_STAY\020\t\022\017\n\013BOOK_FLIGHT\020\n\022\014\n\010BO" +
      "OK_CAR\020\013\022\024\n\020BOOK_APPOINTMENT\020\014\022\027\n\023MEMBER" +
      "SHIP_BENEFITS\020\r\022\t\n\005ORDER\020\016BG\n\020com.passki" +
      "t.grpcZ$stash.passkit.com/io/model/sdk/g" +
      "o/io\252\002\014PassKit.Grpcb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_io_FeaturedAction_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_FeaturedAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_io_FeaturedAction_descriptor,
        new java.lang.String[] { "Identifier", "Type", "Url", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
