// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: io/member/event.proto

package com.passkit.grpc.Members;

public final class Event {
  private Event() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EventDetailsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:members.EventDetails)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Address the event took place.
     * </pre>
     *
     * <code>string address = 1;</code>
     * @return The address.
     */
    java.lang.String getAddress();
    /**
     * <pre>
     * Address the event took place.
     * </pre>
     *
     * <code>string address = 1;</code>
     * @return The bytes for address.
     */
    com.google.protobuf.ByteString
        getAddressBytes();

    /**
     * <pre>
     * Latitude the event took place.
     * </pre>
     *
     * <code>double lat = 2;</code>
     * @return The lat.
     */
    double getLat();

    /**
     * <pre>
     * Longitude the event took place.
     * </pre>
     *
     * <code>double lon = 3;</code>
     * @return The lon.
     */
    double getLon();

    /**
     * <pre>
     * Altitude the event took place (in metres).
     * </pre>
     *
     * <code>int32 alt = 4;</code>
     * @return The alt.
     */
    int getAlt();

    /**
     * <pre>
     * External unique ID of the event.
     * </pre>
     *
     * <code>string externalEventId = 5;</code>
     * @return The externalEventId.
     */
    java.lang.String getExternalEventId();
    /**
     * <pre>
     * External unique ID of the event.
     * </pre>
     *
     * <code>string externalEventId = 5;</code>
     * @return The bytes for externalEventId.
     */
    com.google.protobuf.ByteString
        getExternalEventIdBytes();

    /**
     * <pre>
     * External device ID of the device that was used to capture the event (for example when using an external scanning app).
     * </pre>
     *
     * <code>string externalDeviceId = 6;</code>
     * @return The externalDeviceId.
     */
    java.lang.String getExternalDeviceId();
    /**
     * <pre>
     * External device ID of the device that was used to capture the event (for example when using an external scanning app).
     * </pre>
     *
     * <code>string externalDeviceId = 6;</code>
     * @return The bytes for externalDeviceId.
     */
    com.google.protobuf.ByteString
        getExternalDeviceIdBytes();

    /**
     * <pre>
     * External service ID of the service that was used for capturing the event (for example when using an external scanning app).
     * </pre>
     *
     * <code>string externalServiceId = 7;</code>
     * @return The externalServiceId.
     */
    java.lang.String getExternalServiceId();
    /**
     * <pre>
     * External service ID of the service that was used for capturing the event (for example when using an external scanning app).
     * </pre>
     *
     * <code>string externalServiceId = 7;</code>
     * @return The bytes for externalServiceId.
     */
    com.google.protobuf.ByteString
        getExternalServiceIdBytes();

    /**
     * <pre>
     * Any meta data (for example gathered on scanning) that is relevant to the event (# of points earner, bill spent, device meta-data, etc).
     * </pre>
     *
     * <code>map&lt;string, string&gt; metaData = 8;</code>
     */
    int getMetaDataCount();
    /**
     * <pre>
     * Any meta data (for example gathered on scanning) that is relevant to the event (# of points earner, bill spent, device meta-data, etc).
     * </pre>
     *
     * <code>map&lt;string, string&gt; metaData = 8;</code>
     */
    boolean containsMetaData(
        java.lang.String key);
    /**
     * Use {@link #getMetaDataMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getMetaData();
    /**
     * <pre>
     * Any meta data (for example gathered on scanning) that is relevant to the event (# of points earner, bill spent, device meta-data, etc).
     * </pre>
     *
     * <code>map&lt;string, string&gt; metaData = 8;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getMetaDataMap();
    /**
     * <pre>
     * Any meta data (for example gathered on scanning) that is relevant to the event (# of points earner, bill spent, device meta-data, etc).
     * </pre>
     *
     * <code>map&lt;string, string&gt; metaData = 8;</code>
     */

    java.lang.String getMetaDataOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <pre>
     * Any meta data (for example gathered on scanning) that is relevant to the event (# of points earner, bill spent, device meta-data, etc).
     * </pre>
     *
     * <code>map&lt;string, string&gt; metaData = 8;</code>
     */

    java.lang.String getMetaDataOrThrow(
        java.lang.String key);

    /**
     * <pre>
     * Any relevant notes for the event.
     * </pre>
     *
     * <code>string notes = 9;</code>
     * @return The notes.
     */
    java.lang.String getNotes();
    /**
     * <pre>
     * Any relevant notes for the event.
     * </pre>
     *
     * <code>string notes = 9;</code>
     * @return The bytes for notes.
     */
    com.google.protobuf.ByteString
        getNotesBytes();
  }
  /**
   * <pre>
   * Details on the event. These info will be stored in Member Event.
   * </pre>
   *
   * Protobuf type {@code members.EventDetails}
   */
  public static final class EventDetails extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:members.EventDetails)
      EventDetailsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EventDetails.newBuilder() to construct.
    private EventDetails(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EventDetails() {
      address_ = "";
      externalEventId_ = "";
      externalDeviceId_ = "";
      externalServiceId_ = "";
      notes_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new EventDetails();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EventDetails(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              address_ = s;
              break;
            }
            case 17: {

              lat_ = input.readDouble();
              break;
            }
            case 25: {

              lon_ = input.readDouble();
              break;
            }
            case 32: {

              alt_ = input.readInt32();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              externalEventId_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              externalDeviceId_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              externalServiceId_ = s;
              break;
            }
            case 66: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                metaData_ = com.google.protobuf.MapField.newMapField(
                    MetaDataDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              metaData__ = input.readMessage(
                  MetaDataDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              metaData_.getMutableMap().put(
                  metaData__.getKey(), metaData__.getValue());
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              notes_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.passkit.grpc.Members.Event.internal_static_members_EventDetails_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 8:
          return internalGetMetaData();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.passkit.grpc.Members.Event.internal_static_members_EventDetails_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.passkit.grpc.Members.Event.EventDetails.class, com.passkit.grpc.Members.Event.EventDetails.Builder.class);
    }

    public static final int ADDRESS_FIELD_NUMBER = 1;
    private volatile java.lang.Object address_;
    /**
     * <pre>
     * Address the event took place.
     * </pre>
     *
     * <code>string address = 1;</code>
     * @return The address.
     */
    @java.lang.Override
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Address the event took place.
     * </pre>
     *
     * <code>string address = 1;</code>
     * @return The bytes for address.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LAT_FIELD_NUMBER = 2;
    private double lat_;
    /**
     * <pre>
     * Latitude the event took place.
     * </pre>
     *
     * <code>double lat = 2;</code>
     * @return The lat.
     */
    @java.lang.Override
    public double getLat() {
      return lat_;
    }

    public static final int LON_FIELD_NUMBER = 3;
    private double lon_;
    /**
     * <pre>
     * Longitude the event took place.
     * </pre>
     *
     * <code>double lon = 3;</code>
     * @return The lon.
     */
    @java.lang.Override
    public double getLon() {
      return lon_;
    }

    public static final int ALT_FIELD_NUMBER = 4;
    private int alt_;
    /**
     * <pre>
     * Altitude the event took place (in metres).
     * </pre>
     *
     * <code>int32 alt = 4;</code>
     * @return The alt.
     */
    @java.lang.Override
    public int getAlt() {
      return alt_;
    }

    public static final int EXTERNALEVENTID_FIELD_NUMBER = 5;
    private volatile java.lang.Object externalEventId_;
    /**
     * <pre>
     * External unique ID of the event.
     * </pre>
     *
     * <code>string externalEventId = 5;</code>
     * @return The externalEventId.
     */
    @java.lang.Override
    public java.lang.String getExternalEventId() {
      java.lang.Object ref = externalEventId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        externalEventId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * External unique ID of the event.
     * </pre>
     *
     * <code>string externalEventId = 5;</code>
     * @return The bytes for externalEventId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getExternalEventIdBytes() {
      java.lang.Object ref = externalEventId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        externalEventId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXTERNALDEVICEID_FIELD_NUMBER = 6;
    private volatile java.lang.Object externalDeviceId_;
    /**
     * <pre>
     * External device ID of the device that was used to capture the event (for example when using an external scanning app).
     * </pre>
     *
     * <code>string externalDeviceId = 6;</code>
     * @return The externalDeviceId.
     */
    @java.lang.Override
    public java.lang.String getExternalDeviceId() {
      java.lang.Object ref = externalDeviceId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        externalDeviceId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * External device ID of the device that was used to capture the event (for example when using an external scanning app).
     * </pre>
     *
     * <code>string externalDeviceId = 6;</code>
     * @return The bytes for externalDeviceId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getExternalDeviceIdBytes() {
      java.lang.Object ref = externalDeviceId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        externalDeviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXTERNALSERVICEID_FIELD_NUMBER = 7;
    private volatile java.lang.Object externalServiceId_;
    /**
     * <pre>
     * External service ID of the service that was used for capturing the event (for example when using an external scanning app).
     * </pre>
     *
     * <code>string externalServiceId = 7;</code>
     * @return The externalServiceId.
     */
    @java.lang.Override
    public java.lang.String getExternalServiceId() {
      java.lang.Object ref = externalServiceId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        externalServiceId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * External service ID of the service that was used for capturing the event (for example when using an external scanning app).
     * </pre>
     *
     * <code>string externalServiceId = 7;</code>
     * @return The bytes for externalServiceId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getExternalServiceIdBytes() {
      java.lang.Object ref = externalServiceId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        externalServiceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int METADATA_FIELD_NUMBER = 8;
    private static final class MetaDataDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.passkit.grpc.Members.Event.internal_static_members_EventDetails_MetaDataEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> metaData_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMetaData() {
      if (metaData_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MetaDataDefaultEntryHolder.defaultEntry);
      }
      return metaData_;
    }

    public int getMetaDataCount() {
      return internalGetMetaData().getMap().size();
    }
    /**
     * <pre>
     * Any meta data (for example gathered on scanning) that is relevant to the event (# of points earner, bill spent, device meta-data, etc).
     * </pre>
     *
     * <code>map&lt;string, string&gt; metaData = 8;</code>
     */

    @java.lang.Override
    public boolean containsMetaData(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetMetaData().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMetaDataMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getMetaData() {
      return getMetaDataMap();
    }
    /**
     * <pre>
     * Any meta data (for example gathered on scanning) that is relevant to the event (# of points earner, bill spent, device meta-data, etc).
     * </pre>
     *
     * <code>map&lt;string, string&gt; metaData = 8;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getMetaDataMap() {
      return internalGetMetaData().getMap();
    }
    /**
     * <pre>
     * Any meta data (for example gathered on scanning) that is relevant to the event (# of points earner, bill spent, device meta-data, etc).
     * </pre>
     *
     * <code>map&lt;string, string&gt; metaData = 8;</code>
     */
    @java.lang.Override

    public java.lang.String getMetaDataOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMetaData().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * Any meta data (for example gathered on scanning) that is relevant to the event (# of points earner, bill spent, device meta-data, etc).
     * </pre>
     *
     * <code>map&lt;string, string&gt; metaData = 8;</code>
     */
    @java.lang.Override

    public java.lang.String getMetaDataOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMetaData().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int NOTES_FIELD_NUMBER = 9;
    private volatile java.lang.Object notes_;
    /**
     * <pre>
     * Any relevant notes for the event.
     * </pre>
     *
     * <code>string notes = 9;</code>
     * @return The notes.
     */
    @java.lang.Override
    public java.lang.String getNotes() {
      java.lang.Object ref = notes_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        notes_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Any relevant notes for the event.
     * </pre>
     *
     * <code>string notes = 9;</code>
     * @return The bytes for notes.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNotesBytes() {
      java.lang.Object ref = notes_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        notes_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, address_);
      }
      if (lat_ != 0D) {
        output.writeDouble(2, lat_);
      }
      if (lon_ != 0D) {
        output.writeDouble(3, lon_);
      }
      if (alt_ != 0) {
        output.writeInt32(4, alt_);
      }
      if (!getExternalEventIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, externalEventId_);
      }
      if (!getExternalDeviceIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, externalDeviceId_);
      }
      if (!getExternalServiceIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, externalServiceId_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetMetaData(),
          MetaDataDefaultEntryHolder.defaultEntry,
          8);
      if (!getNotesBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, notes_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, address_);
      }
      if (lat_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, lat_);
      }
      if (lon_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, lon_);
      }
      if (alt_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, alt_);
      }
      if (!getExternalEventIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, externalEventId_);
      }
      if (!getExternalDeviceIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, externalDeviceId_);
      }
      if (!getExternalServiceIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, externalServiceId_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetMetaData().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        metaData__ = MetaDataDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(8, metaData__);
      }
      if (!getNotesBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, notes_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.passkit.grpc.Members.Event.EventDetails)) {
        return super.equals(obj);
      }
      com.passkit.grpc.Members.Event.EventDetails other = (com.passkit.grpc.Members.Event.EventDetails) obj;

      if (!getAddress()
          .equals(other.getAddress())) return false;
      if (java.lang.Double.doubleToLongBits(getLat())
          != java.lang.Double.doubleToLongBits(
              other.getLat())) return false;
      if (java.lang.Double.doubleToLongBits(getLon())
          != java.lang.Double.doubleToLongBits(
              other.getLon())) return false;
      if (getAlt()
          != other.getAlt()) return false;
      if (!getExternalEventId()
          .equals(other.getExternalEventId())) return false;
      if (!getExternalDeviceId()
          .equals(other.getExternalDeviceId())) return false;
      if (!getExternalServiceId()
          .equals(other.getExternalServiceId())) return false;
      if (!internalGetMetaData().equals(
          other.internalGetMetaData())) return false;
      if (!getNotes()
          .equals(other.getNotes())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      hash = (37 * hash) + LAT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getLat()));
      hash = (37 * hash) + LON_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getLon()));
      hash = (37 * hash) + ALT_FIELD_NUMBER;
      hash = (53 * hash) + getAlt();
      hash = (37 * hash) + EXTERNALEVENTID_FIELD_NUMBER;
      hash = (53 * hash) + getExternalEventId().hashCode();
      hash = (37 * hash) + EXTERNALDEVICEID_FIELD_NUMBER;
      hash = (53 * hash) + getExternalDeviceId().hashCode();
      hash = (37 * hash) + EXTERNALSERVICEID_FIELD_NUMBER;
      hash = (53 * hash) + getExternalServiceId().hashCode();
      if (!internalGetMetaData().getMap().isEmpty()) {
        hash = (37 * hash) + METADATA_FIELD_NUMBER;
        hash = (53 * hash) + internalGetMetaData().hashCode();
      }
      hash = (37 * hash) + NOTES_FIELD_NUMBER;
      hash = (53 * hash) + getNotes().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.passkit.grpc.Members.Event.EventDetails parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.passkit.grpc.Members.Event.EventDetails parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.passkit.grpc.Members.Event.EventDetails parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.passkit.grpc.Members.Event.EventDetails parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.passkit.grpc.Members.Event.EventDetails parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.passkit.grpc.Members.Event.EventDetails parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.passkit.grpc.Members.Event.EventDetails parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.passkit.grpc.Members.Event.EventDetails parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.passkit.grpc.Members.Event.EventDetails parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.passkit.grpc.Members.Event.EventDetails parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.passkit.grpc.Members.Event.EventDetails parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.passkit.grpc.Members.Event.EventDetails parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.passkit.grpc.Members.Event.EventDetails prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Details on the event. These info will be stored in Member Event.
     * </pre>
     *
     * Protobuf type {@code members.EventDetails}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:members.EventDetails)
        com.passkit.grpc.Members.Event.EventDetailsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.passkit.grpc.Members.Event.internal_static_members_EventDetails_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 8:
            return internalGetMetaData();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 8:
            return internalGetMutableMetaData();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.passkit.grpc.Members.Event.internal_static_members_EventDetails_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.passkit.grpc.Members.Event.EventDetails.class, com.passkit.grpc.Members.Event.EventDetails.Builder.class);
      }

      // Construct using com.passkit.grpc.Members.Event.EventDetails.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        address_ = "";

        lat_ = 0D;

        lon_ = 0D;

        alt_ = 0;

        externalEventId_ = "";

        externalDeviceId_ = "";

        externalServiceId_ = "";

        internalGetMutableMetaData().clear();
        notes_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.passkit.grpc.Members.Event.internal_static_members_EventDetails_descriptor;
      }

      @java.lang.Override
      public com.passkit.grpc.Members.Event.EventDetails getDefaultInstanceForType() {
        return com.passkit.grpc.Members.Event.EventDetails.getDefaultInstance();
      }

      @java.lang.Override
      public com.passkit.grpc.Members.Event.EventDetails build() {
        com.passkit.grpc.Members.Event.EventDetails result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.passkit.grpc.Members.Event.EventDetails buildPartial() {
        com.passkit.grpc.Members.Event.EventDetails result = new com.passkit.grpc.Members.Event.EventDetails(this);
        int from_bitField0_ = bitField0_;
        result.address_ = address_;
        result.lat_ = lat_;
        result.lon_ = lon_;
        result.alt_ = alt_;
        result.externalEventId_ = externalEventId_;
        result.externalDeviceId_ = externalDeviceId_;
        result.externalServiceId_ = externalServiceId_;
        result.metaData_ = internalGetMetaData();
        result.metaData_.makeImmutable();
        result.notes_ = notes_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.passkit.grpc.Members.Event.EventDetails) {
          return mergeFrom((com.passkit.grpc.Members.Event.EventDetails)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.passkit.grpc.Members.Event.EventDetails other) {
        if (other == com.passkit.grpc.Members.Event.EventDetails.getDefaultInstance()) return this;
        if (!other.getAddress().isEmpty()) {
          address_ = other.address_;
          onChanged();
        }
        if (other.getLat() != 0D) {
          setLat(other.getLat());
        }
        if (other.getLon() != 0D) {
          setLon(other.getLon());
        }
        if (other.getAlt() != 0) {
          setAlt(other.getAlt());
        }
        if (!other.getExternalEventId().isEmpty()) {
          externalEventId_ = other.externalEventId_;
          onChanged();
        }
        if (!other.getExternalDeviceId().isEmpty()) {
          externalDeviceId_ = other.externalDeviceId_;
          onChanged();
        }
        if (!other.getExternalServiceId().isEmpty()) {
          externalServiceId_ = other.externalServiceId_;
          onChanged();
        }
        internalGetMutableMetaData().mergeFrom(
            other.internalGetMetaData());
        if (!other.getNotes().isEmpty()) {
          notes_ = other.notes_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.passkit.grpc.Members.Event.EventDetails parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.passkit.grpc.Members.Event.EventDetails) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object address_ = "";
      /**
       * <pre>
       * Address the event took place.
       * </pre>
       *
       * <code>string address = 1;</code>
       * @return The address.
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Address the event took place.
       * </pre>
       *
       * <code>string address = 1;</code>
       * @return The bytes for address.
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Address the event took place.
       * </pre>
       *
       * <code>string address = 1;</code>
       * @param value The address to set.
       * @return This builder for chaining.
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Address the event took place.
       * </pre>
       *
       * <code>string address = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAddress() {
        
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Address the event took place.
       * </pre>
       *
       * <code>string address = 1;</code>
       * @param value The bytes for address to set.
       * @return This builder for chaining.
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        address_ = value;
        onChanged();
        return this;
      }

      private double lat_ ;
      /**
       * <pre>
       * Latitude the event took place.
       * </pre>
       *
       * <code>double lat = 2;</code>
       * @return The lat.
       */
      @java.lang.Override
      public double getLat() {
        return lat_;
      }
      /**
       * <pre>
       * Latitude the event took place.
       * </pre>
       *
       * <code>double lat = 2;</code>
       * @param value The lat to set.
       * @return This builder for chaining.
       */
      public Builder setLat(double value) {
        
        lat_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Latitude the event took place.
       * </pre>
       *
       * <code>double lat = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLat() {
        
        lat_ = 0D;
        onChanged();
        return this;
      }

      private double lon_ ;
      /**
       * <pre>
       * Longitude the event took place.
       * </pre>
       *
       * <code>double lon = 3;</code>
       * @return The lon.
       */
      @java.lang.Override
      public double getLon() {
        return lon_;
      }
      /**
       * <pre>
       * Longitude the event took place.
       * </pre>
       *
       * <code>double lon = 3;</code>
       * @param value The lon to set.
       * @return This builder for chaining.
       */
      public Builder setLon(double value) {
        
        lon_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Longitude the event took place.
       * </pre>
       *
       * <code>double lon = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLon() {
        
        lon_ = 0D;
        onChanged();
        return this;
      }

      private int alt_ ;
      /**
       * <pre>
       * Altitude the event took place (in metres).
       * </pre>
       *
       * <code>int32 alt = 4;</code>
       * @return The alt.
       */
      @java.lang.Override
      public int getAlt() {
        return alt_;
      }
      /**
       * <pre>
       * Altitude the event took place (in metres).
       * </pre>
       *
       * <code>int32 alt = 4;</code>
       * @param value The alt to set.
       * @return This builder for chaining.
       */
      public Builder setAlt(int value) {
        
        alt_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Altitude the event took place (in metres).
       * </pre>
       *
       * <code>int32 alt = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearAlt() {
        
        alt_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object externalEventId_ = "";
      /**
       * <pre>
       * External unique ID of the event.
       * </pre>
       *
       * <code>string externalEventId = 5;</code>
       * @return The externalEventId.
       */
      public java.lang.String getExternalEventId() {
        java.lang.Object ref = externalEventId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          externalEventId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * External unique ID of the event.
       * </pre>
       *
       * <code>string externalEventId = 5;</code>
       * @return The bytes for externalEventId.
       */
      public com.google.protobuf.ByteString
          getExternalEventIdBytes() {
        java.lang.Object ref = externalEventId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          externalEventId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * External unique ID of the event.
       * </pre>
       *
       * <code>string externalEventId = 5;</code>
       * @param value The externalEventId to set.
       * @return This builder for chaining.
       */
      public Builder setExternalEventId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        externalEventId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * External unique ID of the event.
       * </pre>
       *
       * <code>string externalEventId = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearExternalEventId() {
        
        externalEventId_ = getDefaultInstance().getExternalEventId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * External unique ID of the event.
       * </pre>
       *
       * <code>string externalEventId = 5;</code>
       * @param value The bytes for externalEventId to set.
       * @return This builder for chaining.
       */
      public Builder setExternalEventIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        externalEventId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object externalDeviceId_ = "";
      /**
       * <pre>
       * External device ID of the device that was used to capture the event (for example when using an external scanning app).
       * </pre>
       *
       * <code>string externalDeviceId = 6;</code>
       * @return The externalDeviceId.
       */
      public java.lang.String getExternalDeviceId() {
        java.lang.Object ref = externalDeviceId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          externalDeviceId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * External device ID of the device that was used to capture the event (for example when using an external scanning app).
       * </pre>
       *
       * <code>string externalDeviceId = 6;</code>
       * @return The bytes for externalDeviceId.
       */
      public com.google.protobuf.ByteString
          getExternalDeviceIdBytes() {
        java.lang.Object ref = externalDeviceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          externalDeviceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * External device ID of the device that was used to capture the event (for example when using an external scanning app).
       * </pre>
       *
       * <code>string externalDeviceId = 6;</code>
       * @param value The externalDeviceId to set.
       * @return This builder for chaining.
       */
      public Builder setExternalDeviceId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        externalDeviceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * External device ID of the device that was used to capture the event (for example when using an external scanning app).
       * </pre>
       *
       * <code>string externalDeviceId = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearExternalDeviceId() {
        
        externalDeviceId_ = getDefaultInstance().getExternalDeviceId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * External device ID of the device that was used to capture the event (for example when using an external scanning app).
       * </pre>
       *
       * <code>string externalDeviceId = 6;</code>
       * @param value The bytes for externalDeviceId to set.
       * @return This builder for chaining.
       */
      public Builder setExternalDeviceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        externalDeviceId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object externalServiceId_ = "";
      /**
       * <pre>
       * External service ID of the service that was used for capturing the event (for example when using an external scanning app).
       * </pre>
       *
       * <code>string externalServiceId = 7;</code>
       * @return The externalServiceId.
       */
      public java.lang.String getExternalServiceId() {
        java.lang.Object ref = externalServiceId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          externalServiceId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * External service ID of the service that was used for capturing the event (for example when using an external scanning app).
       * </pre>
       *
       * <code>string externalServiceId = 7;</code>
       * @return The bytes for externalServiceId.
       */
      public com.google.protobuf.ByteString
          getExternalServiceIdBytes() {
        java.lang.Object ref = externalServiceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          externalServiceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * External service ID of the service that was used for capturing the event (for example when using an external scanning app).
       * </pre>
       *
       * <code>string externalServiceId = 7;</code>
       * @param value The externalServiceId to set.
       * @return This builder for chaining.
       */
      public Builder setExternalServiceId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        externalServiceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * External service ID of the service that was used for capturing the event (for example when using an external scanning app).
       * </pre>
       *
       * <code>string externalServiceId = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearExternalServiceId() {
        
        externalServiceId_ = getDefaultInstance().getExternalServiceId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * External service ID of the service that was used for capturing the event (for example when using an external scanning app).
       * </pre>
       *
       * <code>string externalServiceId = 7;</code>
       * @param value The bytes for externalServiceId to set.
       * @return This builder for chaining.
       */
      public Builder setExternalServiceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        externalServiceId_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> metaData_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMetaData() {
        if (metaData_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              MetaDataDefaultEntryHolder.defaultEntry);
        }
        return metaData_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableMetaData() {
        onChanged();;
        if (metaData_ == null) {
          metaData_ = com.google.protobuf.MapField.newMapField(
              MetaDataDefaultEntryHolder.defaultEntry);
        }
        if (!metaData_.isMutable()) {
          metaData_ = metaData_.copy();
        }
        return metaData_;
      }

      public int getMetaDataCount() {
        return internalGetMetaData().getMap().size();
      }
      /**
       * <pre>
       * Any meta data (for example gathered on scanning) that is relevant to the event (# of points earner, bill spent, device meta-data, etc).
       * </pre>
       *
       * <code>map&lt;string, string&gt; metaData = 8;</code>
       */

      @java.lang.Override
      public boolean containsMetaData(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetMetaData().getMap().containsKey(key);
      }
      /**
       * Use {@link #getMetaDataMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getMetaData() {
        return getMetaDataMap();
      }
      /**
       * <pre>
       * Any meta data (for example gathered on scanning) that is relevant to the event (# of points earner, bill spent, device meta-data, etc).
       * </pre>
       *
       * <code>map&lt;string, string&gt; metaData = 8;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.String, java.lang.String> getMetaDataMap() {
        return internalGetMetaData().getMap();
      }
      /**
       * <pre>
       * Any meta data (for example gathered on scanning) that is relevant to the event (# of points earner, bill spent, device meta-data, etc).
       * </pre>
       *
       * <code>map&lt;string, string&gt; metaData = 8;</code>
       */
      @java.lang.Override

      public java.lang.String getMetaDataOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetMetaData().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       * Any meta data (for example gathered on scanning) that is relevant to the event (# of points earner, bill spent, device meta-data, etc).
       * </pre>
       *
       * <code>map&lt;string, string&gt; metaData = 8;</code>
       */
      @java.lang.Override

      public java.lang.String getMetaDataOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetMetaData().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearMetaData() {
        internalGetMutableMetaData().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       * Any meta data (for example gathered on scanning) that is relevant to the event (# of points earner, bill spent, device meta-data, etc).
       * </pre>
       *
       * <code>map&lt;string, string&gt; metaData = 8;</code>
       */

      public Builder removeMetaData(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableMetaData().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableMetaData() {
        return internalGetMutableMetaData().getMutableMap();
      }
      /**
       * <pre>
       * Any meta data (for example gathered on scanning) that is relevant to the event (# of points earner, bill spent, device meta-data, etc).
       * </pre>
       *
       * <code>map&lt;string, string&gt; metaData = 8;</code>
       */
      public Builder putMetaData(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableMetaData().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <pre>
       * Any meta data (for example gathered on scanning) that is relevant to the event (# of points earner, bill spent, device meta-data, etc).
       * </pre>
       *
       * <code>map&lt;string, string&gt; metaData = 8;</code>
       */

      public Builder putAllMetaData(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableMetaData().getMutableMap()
            .putAll(values);
        return this;
      }

      private java.lang.Object notes_ = "";
      /**
       * <pre>
       * Any relevant notes for the event.
       * </pre>
       *
       * <code>string notes = 9;</code>
       * @return The notes.
       */
      public java.lang.String getNotes() {
        java.lang.Object ref = notes_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          notes_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Any relevant notes for the event.
       * </pre>
       *
       * <code>string notes = 9;</code>
       * @return The bytes for notes.
       */
      public com.google.protobuf.ByteString
          getNotesBytes() {
        java.lang.Object ref = notes_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          notes_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Any relevant notes for the event.
       * </pre>
       *
       * <code>string notes = 9;</code>
       * @param value The notes to set.
       * @return This builder for chaining.
       */
      public Builder setNotes(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        notes_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Any relevant notes for the event.
       * </pre>
       *
       * <code>string notes = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearNotes() {
        
        notes_ = getDefaultInstance().getNotes();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Any relevant notes for the event.
       * </pre>
       *
       * <code>string notes = 9;</code>
       * @param value The bytes for notes to set.
       * @return This builder for chaining.
       */
      public Builder setNotesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        notes_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:members.EventDetails)
    }

    // @@protoc_insertion_point(class_scope:members.EventDetails)
    private static final com.passkit.grpc.Members.Event.EventDetails DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.passkit.grpc.Members.Event.EventDetails();
    }

    public static com.passkit.grpc.Members.Event.EventDetails getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EventDetails>
        PARSER = new com.google.protobuf.AbstractParser<EventDetails>() {
      @java.lang.Override
      public EventDetails parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EventDetails(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EventDetails> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EventDetails> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.passkit.grpc.Members.Event.EventDetails getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_members_EventDetails_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_members_EventDetails_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_members_EventDetails_MetaDataEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_members_EventDetails_MetaDataEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025io/member/event.proto\022\007members\"\213\002\n\014Eve" +
      "ntDetails\022\017\n\007address\030\001 \001(\t\022\013\n\003lat\030\002 \001(\001\022" +
      "\013\n\003lon\030\003 \001(\001\022\013\n\003alt\030\004 \001(\005\022\027\n\017externalEve" +
      "ntId\030\005 \001(\t\022\030\n\020externalDeviceId\030\006 \001(\t\022\031\n\021" +
      "externalServiceId\030\007 \001(\t\0225\n\010metaData\030\010 \003(" +
      "\0132#.members.EventDetails.MetaDataEntry\022\r" +
      "\n\005notes\030\t \001(\t\032/\n\rMetaDataEntry\022\013\n\003key\030\001 " +
      "\001(\t\022\r\n\005value\030\002 \001(\t:\0028\001B_\n\030com.passkit.gr" +
      "pc.MembersZ,stash.passkit.com/io/model/s" +
      "dk/go/io/members\252\002\024PassKit.Grpc.Membersb" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_members_EventDetails_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_members_EventDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_members_EventDetails_descriptor,
        new java.lang.String[] { "Address", "Lat", "Lon", "Alt", "ExternalEventId", "ExternalDeviceId", "ExternalServiceId", "MetaData", "Notes", });
    internal_static_members_EventDetails_MetaDataEntry_descriptor =
      internal_static_members_EventDetails_descriptor.getNestedTypes().get(0);
    internal_static_members_EventDetails_MetaDataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_members_EventDetails_MetaDataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
